// Stats are approximate and reflect career totals through the 2024 F1 season.
export type DriverStatus = 'Active' | 'Retired'
export type DriverEra = 'Modern' | 'Legends' // Modern = 2010+ debut; Legends = pre-2010 debut

export interface Driver {
  id: string
  name: string
  nationality: string
  championships: number
  wins: number
  poles: number
  debutYear: number
  status: DriverStatus
  teams: string[]
  era: DriverEra
  isWorldChampion: boolean
}

export const DRIVERS: Driver[] = [
  // ── Modern era (debut 2010+) ─────────────────────────────────────────────
  {
    id: 'max-verstappen',
    name: 'Max Verstappen',
    nationality: 'Dutch',
    championships: 4,
    wins: 63,
    poles: 40,
    debutYear: 2015,
    status: 'Active',
    teams: ['Toro Rosso', 'Red Bull'],
    era: 'Modern',
    isWorldChampion: true,
  },
  {
    id: 'lando-norris',
    name: 'Lando Norris',
    nationality: 'British',
    championships: 1,
    wins: 6,
    poles: 14,
    debutYear: 2019,
    status: 'Active',
    teams: ['McLaren'],
    era: 'Modern',
    isWorldChampion: true,
  },
  {
    id: 'charles-leclerc',
    name: 'Charles Leclerc',
    nationality: 'Monégasque',
    championships: 0,
    wins: 8,
    poles: 26,
    debutYear: 2018,
    status: 'Active',
    teams: ['Sauber', 'Ferrari'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'george-russell',
    name: 'George Russell',
    nationality: 'British',
    championships: 0,
    wins: 2,
    poles: 2,
    debutYear: 2019,
    status: 'Active',
    teams: ['Williams', 'Mercedes'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'oscar-piastri',
    name: 'Oscar Piastri',
    nationality: 'Australian',
    championships: 0,
    wins: 3,
    poles: 2,
    debutYear: 2023,
    status: 'Active',
    teams: ['McLaren'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'carlos-sainz',
    name: 'Carlos Sainz',
    nationality: 'Spanish',
    championships: 0,
    wins: 4,
    poles: 5,
    debutYear: 2015,
    status: 'Active',
    teams: ['Toro Rosso', 'Renault', 'McLaren', 'Ferrari', 'Williams'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'sergio-perez',
    name: 'Sergio Pérez',
    nationality: 'Mexican',
    championships: 0,
    wins: 6,
    poles: 3,
    debutYear: 2011,
    status: 'Retired',
    teams: ['Sauber', 'McLaren', 'Force India', 'Racing Point', 'Red Bull'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'valtteri-bottas',
    name: 'Valtteri Bottas',
    nationality: 'Finnish',
    championships: 0,
    wins: 10,
    poles: 20,
    debutYear: 2013,
    status: 'Active',
    teams: ['Williams', 'Mercedes', 'Alfa Romeo'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'daniel-ricciardo',
    name: 'Daniel Ricciardo',
    nationality: 'Australian',
    championships: 0,
    wins: 8,
    poles: 3,
    debutYear: 2011,
    status: 'Retired',
    teams: ['HRT', 'Toro Rosso', 'Red Bull', 'Renault', 'McLaren', 'AlphaTauri'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'nico-hulkenberg',
    name: 'Nico Hülkenberg',
    nationality: 'German',
    championships: 0,
    wins: 0,
    poles: 1,
    debutYear: 2010,
    status: 'Active',
    teams: ['Williams', 'Force India', 'Sauber', 'Renault', 'Racing Point', 'Haas'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'pierre-gasly',
    name: 'Pierre Gasly',
    nationality: 'French',
    championships: 0,
    wins: 1,
    poles: 0,
    debutYear: 2017,
    status: 'Active',
    teams: ['Toro Rosso', 'Red Bull', 'AlphaTauri', 'Alpine'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'esteban-ocon',
    name: 'Esteban Ocon',
    nationality: 'French',
    championships: 0,
    wins: 1,
    poles: 0,
    debutYear: 2016,
    status: 'Active',
    teams: ['Manor', 'Force India', 'Racing Point', 'Renault', 'Alpine', 'Haas'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'lance-stroll',
    name: 'Lance Stroll',
    nationality: 'Canadian',
    championships: 0,
    wins: 0,
    poles: 1,
    debutYear: 2017,
    status: 'Active',
    teams: ['Williams', 'Racing Point', 'Aston Martin'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'yuki-tsunoda',
    name: 'Yuki Tsunoda',
    nationality: 'Japanese',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2021,
    status: 'Active',
    teams: ['AlphaTauri', 'RB'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'alex-albon',
    name: 'Alex Albon',
    nationality: 'Thai',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2019,
    status: 'Active',
    teams: ['Toro Rosso', 'Red Bull', 'Williams'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'kevin-magnussen',
    name: 'Kevin Magnussen',
    nationality: 'Danish',
    championships: 0,
    wins: 0,
    poles: 1,
    debutYear: 2014,
    status: 'Active',
    teams: ['McLaren', 'Renault', 'Haas'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'mick-schumacher',
    name: 'Mick Schumacher',
    nationality: 'German',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2021,
    status: 'Retired',
    teams: ['Haas'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'daniil-kvyat',
    name: 'Daniil Kvyat',
    nationality: 'Russian',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2014,
    status: 'Retired',
    teams: ['Toro Rosso', 'Red Bull', 'AlphaTauri'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'pastor-maldonado',
    name: 'Pastor Maldonado',
    nationality: 'Venezuelan',
    championships: 0,
    wins: 1,
    poles: 1,
    debutYear: 2011,
    status: 'Retired',
    teams: ['Williams', 'Lotus'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'antonio-giovinazzi',
    name: 'Antonio Giovinazzi',
    nationality: 'Italian',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2017,
    status: 'Retired',
    teams: ['Sauber', 'Alfa Romeo'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'zhou-guanyu',
    name: 'Zhou Guanyu',
    nationality: 'Chinese',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2022,
    status: 'Active',
    teams: ['Alfa Romeo'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'nyck-de-vries',
    name: 'Nyck de Vries',
    nationality: 'Dutch',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2023,
    status: 'Retired',
    teams: ['AlphaTauri'],
    era: 'Modern',
    isWorldChampion: false,
  },
  {
    id: 'paul-di-resta',
    name: 'Paul di Resta',
    nationality: 'British',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2011,
    status: 'Retired',
    teams: ['Force India', 'Williams'],
    era: 'Modern',
    isWorldChampion: false,
  },

  // ── Legends era (debut pre-2010) ─────────────────────────────────────────
  {
    id: 'lewis-hamilton',
    name: 'Lewis Hamilton',
    nationality: 'British',
    championships: 7,
    wins: 103,
    poles: 103,
    debutYear: 2007,
    status: 'Active',
    teams: ['McLaren', 'Mercedes', 'Ferrari'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'sebastian-vettel',
    name: 'Sebastian Vettel',
    nationality: 'German',
    championships: 4,
    wins: 53,
    poles: 57,
    debutYear: 2007,
    status: 'Retired',
    teams: ['BMW Sauber', 'Toro Rosso', 'Red Bull', 'Ferrari', 'Aston Martin'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'fernando-alonso',
    name: 'Fernando Alonso',
    nationality: 'Spanish',
    championships: 2,
    wins: 32,
    poles: 22,
    debutYear: 2001,
    status: 'Active',
    teams: ['Minardi', 'Renault', 'McLaren', 'Ferrari', 'Alpine', 'Aston Martin'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'kimi-raikkonen',
    name: 'Kimi Räikkönen',
    nationality: 'Finnish',
    championships: 1,
    wins: 21,
    poles: 18,
    debutYear: 2001,
    status: 'Retired',
    teams: ['Sauber', 'McLaren', 'Ferrari', 'Lotus', 'Alfa Romeo'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'jenson-button',
    name: 'Jenson Button',
    nationality: 'British',
    championships: 1,
    wins: 15,
    poles: 8,
    debutYear: 2000,
    status: 'Retired',
    teams: ['Williams', 'Benetton', 'Renault', 'BAR', 'Honda', 'Brawn', 'McLaren'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'nico-rosberg',
    name: 'Nico Rosberg',
    nationality: 'German',
    championships: 1,
    wins: 23,
    poles: 30,
    debutYear: 2006,
    status: 'Retired',
    teams: ['Williams', 'Mercedes'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'michael-schumacher',
    name: 'Michael Schumacher',
    nationality: 'German',
    championships: 7,
    wins: 91,
    poles: 68,
    debutYear: 1991,
    status: 'Retired',
    teams: ['Jordan', 'Benetton', 'Ferrari', 'Mercedes'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'ayrton-senna',
    name: 'Ayrton Senna',
    nationality: 'Brazilian',
    championships: 3,
    wins: 41,
    poles: 65,
    debutYear: 1984,
    status: 'Retired',
    teams: ['Toleman', 'Lotus', 'McLaren', 'Williams'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'alain-prost',
    name: 'Alain Prost',
    nationality: 'French',
    championships: 4,
    wins: 51,
    poles: 33,
    debutYear: 1980,
    status: 'Retired',
    teams: ['McLaren', 'Renault', 'Ferrari', 'Williams'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'mika-hakkinen',
    name: 'Mika Häkkinen',
    nationality: 'Finnish',
    championships: 2,
    wins: 20,
    poles: 26,
    debutYear: 1991,
    status: 'Retired',
    teams: ['Lotus', 'McLaren'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'damon-hill',
    name: 'Damon Hill',
    nationality: 'British',
    championships: 1,
    wins: 22,
    poles: 20,
    debutYear: 1992,
    status: 'Retired',
    teams: ['Brabham', 'Williams', 'Arrows', 'Jordan'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'nigel-mansell',
    name: 'Nigel Mansell',
    nationality: 'British',
    championships: 1,
    wins: 31,
    poles: 32,
    debutYear: 1980,
    status: 'Retired',
    teams: ['Lotus', 'Williams', 'Ferrari', 'McLaren'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'nelson-piquet',
    name: 'Nelson Piquet',
    nationality: 'Brazilian',
    championships: 3,
    wins: 23,
    poles: 24,
    debutYear: 1978,
    status: 'Retired',
    teams: ['Brabham', 'Williams', 'Lotus', 'Benetton'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'niki-lauda',
    name: 'Niki Lauda',
    nationality: 'Austrian',
    championships: 2,
    wins: 25,
    poles: 24,
    debutYear: 1971,
    status: 'Retired',
    teams: ['March', 'BRM', 'Ferrari', 'Brabham', 'McLaren'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'jackie-stewart',
    name: 'Jackie Stewart',
    nationality: 'British',
    championships: 3,
    wins: 27,
    poles: 17,
    debutYear: 1965,
    status: 'Retired',
    teams: ['BRM', 'Matra', 'March', 'Tyrrell'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'jim-clark',
    name: 'Jim Clark',
    nationality: 'British',
    championships: 2,
    wins: 25,
    poles: 33,
    debutYear: 1960,
    status: 'Retired',
    teams: ['Lotus'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'emerson-fittipaldi',
    name: 'Emerson Fittipaldi',
    nationality: 'Brazilian',
    championships: 2,
    wins: 14,
    poles: 6,
    debutYear: 1970,
    status: 'Retired',
    teams: ['Lotus', 'McLaren', 'Fittipaldi'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'jack-brabham',
    name: 'Jack Brabham',
    nationality: 'Australian',
    championships: 3,
    wins: 14,
    poles: 13,
    debutYear: 1955,
    status: 'Retired',
    teams: ['Cooper', 'Brabham'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'graham-hill',
    name: 'Graham Hill',
    nationality: 'British',
    championships: 2,
    wins: 14,
    poles: 13,
    debutYear: 1958,
    status: 'Retired',
    teams: ['Lotus', 'BRM', 'Brabham'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'jochen-rindt',
    name: 'Jochen Rindt',
    nationality: 'Austrian',
    championships: 1,
    wins: 6,
    poles: 10,
    debutYear: 1964,
    status: 'Retired',
    teams: ['Cooper', 'Brabham', 'Lotus'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'mario-andretti',
    name: 'Mario Andretti',
    nationality: 'American',
    championships: 1,
    wins: 12,
    poles: 18,
    debutYear: 1968,
    status: 'Retired',
    teams: ['Lotus', 'Ferrari', 'Alfa Romeo'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'jacques-villeneuve',
    name: 'Jacques Villeneuve',
    nationality: 'Canadian',
    championships: 1,
    wins: 11,
    poles: 13,
    debutYear: 1996,
    status: 'Retired',
    teams: ['Williams', 'BAR', 'Renault', 'BMW Sauber', 'HRT'],
    era: 'Legends',
    isWorldChampion: true,
  },
  {
    id: 'rubens-barrichello',
    name: 'Rubens Barrichello',
    nationality: 'Brazilian',
    championships: 0,
    wins: 11,
    poles: 14,
    debutYear: 1993,
    status: 'Retired',
    teams: ['Jordan', 'Stewart', 'Ferrari', 'Honda', 'Brawn', 'Williams'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'david-coulthard',
    name: 'David Coulthard',
    nationality: 'British',
    championships: 0,
    wins: 13,
    poles: 12,
    debutYear: 1994,
    status: 'Retired',
    teams: ['Williams', 'McLaren', 'Red Bull'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'mark-webber',
    name: 'Mark Webber',
    nationality: 'Australian',
    championships: 0,
    wins: 9,
    poles: 13,
    debutYear: 2002,
    status: 'Retired',
    teams: ['Minardi', 'Jaguar', 'Williams', 'Red Bull'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'felipe-massa',
    name: 'Felipe Massa',
    nationality: 'Brazilian',
    championships: 0,
    wins: 11,
    poles: 16,
    debutYear: 2002,
    status: 'Retired',
    teams: ['Sauber', 'Ferrari', 'Williams'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'ralf-schumacher',
    name: 'Ralf Schumacher',
    nationality: 'German',
    championships: 0,
    wins: 6,
    poles: 7,
    debutYear: 1997,
    status: 'Retired',
    teams: ['Jordan', 'Williams', 'Toyota'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'juan-pablo-montoya',
    name: 'Juan Pablo Montoya',
    nationality: 'Colombian',
    championships: 0,
    wins: 7,
    poles: 13,
    debutYear: 2001,
    status: 'Retired',
    teams: ['Williams', 'McLaren'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'gilles-villeneuve',
    name: 'Gilles Villeneuve',
    nationality: 'Canadian',
    championships: 0,
    wins: 6,
    poles: 2,
    debutYear: 1977,
    status: 'Retired',
    teams: ['McLaren', 'Ferrari'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'giancarlo-fisichella',
    name: 'Giancarlo Fisichella',
    nationality: 'Italian',
    championships: 0,
    wins: 3,
    poles: 4,
    debutYear: 1996,
    status: 'Retired',
    teams: ['Minardi', 'Jordan', 'Benetton', 'Renault', 'Sauber', 'Force India', 'Ferrari'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'heinz-harald-frentzen',
    name: 'Heinz-Harald Frentzen',
    nationality: 'German',
    championships: 0,
    wins: 3,
    poles: 2,
    debutYear: 1994,
    status: 'Retired',
    teams: ['Sauber', 'Williams', 'Jordan', 'Prost', 'Arrows'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'romain-grosjean',
    name: 'Romain Grosjean',
    nationality: 'French',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2009,
    status: 'Retired',
    teams: ['Renault', 'Lotus', 'Haas'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'eddie-irvine',
    name: 'Eddie Irvine',
    nationality: 'British',
    championships: 0,
    wins: 4,
    poles: 0,
    debutYear: 1993,
    status: 'Retired',
    teams: ['Jordan', 'Ferrari', 'Jaguar'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'jarno-trulli',
    name: 'Jarno Trulli',
    nationality: 'Italian',
    championships: 0,
    wins: 1,
    poles: 4,
    debutYear: 1997,
    status: 'Retired',
    teams: ['Minardi', 'Prost', 'Jordan', 'Renault', 'Toyota', 'Lotus'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'robert-kubica',
    name: 'Robert Kubica',
    nationality: 'Polish',
    championships: 0,
    wins: 1,
    poles: 1,
    debutYear: 2006,
    status: 'Retired',
    teams: ['BMW Sauber', 'Renault', 'Williams'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'heikki-kovalainen',
    name: 'Heikki Kovalainen',
    nationality: 'Finnish',
    championships: 0,
    wins: 1,
    poles: 1,
    debutYear: 2007,
    status: 'Retired',
    teams: ['Renault', 'McLaren', 'Lotus', 'Caterham'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'nick-heidfeld',
    name: 'Nick Heidfeld',
    nationality: 'German',
    championships: 0,
    wins: 0,
    poles: 1,
    debutYear: 2000,
    status: 'Retired',
    teams: ['Prost', 'Sauber', 'Jordan', 'BMW Sauber', 'Mercedes', 'Renault', 'Williams'],
    era: 'Legends',
    isWorldChampion: false,
  },
  {
    id: 'timo-glock',
    name: 'Timo Glock',
    nationality: 'German',
    championships: 0,
    wins: 0,
    poles: 0,
    debutYear: 2004,
    status: 'Retired',
    teams: ['Jordan', 'Toyota', 'Virgin'],
    era: 'Legends',
    isWorldChampion: false,
  },
]

// ── Pool helpers ────────────────────────────────────────────────────────────

export function getPool(difficulty: Difficulty): Driver[] {
  switch (difficulty) {
    case 'rookie':    return DRIVERS.filter(d => d.isWorldChampion)
    case 'modern':    return DRIVERS.filter(d => d.era === 'Modern')
    case 'legends':   return DRIVERS.filter(d => d.era === 'Legends')
    case 'ultimate':  return DRIVERS
  }
}

export type Difficulty = 'rookie' | 'modern' | 'legends' | 'ultimate'

export function getDailyDriver(pool: Driver[]): Driver {
  const d = new Date()
  const seed = d.getFullYear() * 10000 + (d.getMonth() + 1) * 100 + d.getDate()
  return pool[Math.abs(seed) % pool.length]
}

export function getDailyKey(difficulty: Difficulty): string {
  const d = new Date()
  return `predict_daily_${difficulty}_${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`
}

// ── Hint logic ──────────────────────────────────────────────────────────────

export type HintColor = 'green' | 'yellow' | 'red'
export type HintDirection = 'up' | 'down' | null

export interface CellHint {
  color: HintColor
  direction: HintDirection
  display: string
}

export interface GuessHints {
  nationality: CellHint
  championships: CellHint
  wins: CellHint
  poles: CellHint
  debutYear: CellHint
  status: CellHint
  teams: CellHint
}

export interface GuessResult {
  driver: Driver
  hints: GuessHints
}

function numericHint(
  guessVal: number,
  mysteryVal: number,
  closeRange: number,
  display: string,
): CellHint {
  if (guessVal === mysteryVal) return { color: 'green', direction: null, display }
  const close = Math.abs(guessVal - mysteryVal) <= closeRange
  if (close) return { color: 'yellow', direction: null, display }
  return { color: 'red', direction: guessVal < mysteryVal ? 'up' : 'down', display }
}

export function buildHints(guess: Driver, mystery: Driver): GuessHints {
  const sameTeams =
    guess.teams.length === mystery.teams.length &&
    guess.teams.every(t => mystery.teams.includes(t))
  const anySharedTeam = guess.teams.some(t => mystery.teams.includes(t))
  const teamDisplay = guess.teams.slice(0, 2).join(', ') + (guess.teams.length > 2 ? ` +${guess.teams.length - 2}` : '')

  return {
    nationality: {
      color: guess.nationality === mystery.nationality ? 'green' : 'red',
      direction: null,
      display: guess.nationality,
    },
    championships: numericHint(guess.championships, mystery.championships, 1, String(guess.championships)),
    wins: numericHint(guess.wins, mystery.wins, 5, String(guess.wins)),
    poles: numericHint(guess.poles, mystery.poles, 5, String(guess.poles)),
    debutYear: numericHint(guess.debutYear, mystery.debutYear, 2, String(guess.debutYear)),
    status: {
      color: guess.status === mystery.status ? 'green' : 'red',
      direction: null,
      display: guess.status,
    },
    teams: {
      color: sameTeams ? 'green' : anySharedTeam ? 'yellow' : 'red',
      direction: null,
      display: teamDisplay,
    },
  }
}
