export interface RadioQuote {
  id: string
  quote: string
  driver: string
  options: [string, string, string, string]
  context: string
  year: number
  race: string
}

// options[0] is always the correct driver — shuffle in the component
export const RADIO_QUOTES: RadioQuote[] = [
  {
    id: 'r01',
    quote: "Leave me alone, I know what I'm doing.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Sebastian Vettel', 'Fernando Alonso', 'Lewis Hamilton'],
    context: "Räikkönen's engineer kept giving him gap updates during the 2012 Abu Dhabi GP. Kimi had it completely under control — and won the race.",
    year: 2012,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r02',
    quote: "GP2 engine! GP2 engine! Argh!",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Jenson Button', 'Romain Grosjean', 'Kevin Magnussen'],
    context: "Alonso's legendary explosion of frustration at the 2015 Malaysian GP after being lapped. McLaren's Honda engine was producing GP2-level power — in an F1 car.",
    year: 2015,
    race: 'Malaysian GP',
  },
  {
    id: 'r03',
    quote: "I am the world champion! I am the world champion! Oh my god!",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Mark Webber', 'Fernando Alonso', 'Jenson Button'],
    context: "Vettel's raw, barely-believing reaction when he clinched his first of four consecutive championships at the 2010 Japanese GP. He was just 23 years old.",
    year: 2010,
    race: 'Japanese GP',
  },
  {
    id: 'r04',
    quote: "Oh my god, I'm world champion!",
    driver: 'Jenson Button',
    options: ['Jenson Button', 'Rubens Barrichello', 'Lewis Hamilton', 'Kimi Räikkönen'],
    context: "Button's shocked joy after winning the 2009 Brazilian GP, sealing his only world title with the Brawn GP team — a near-bankrupt outfit that came from nowhere.",
    year: 2009,
    race: 'Brazilian GP',
  },
  {
    id: 'r05',
    quote: "Not bad for a number two driver.",
    driver: 'Mark Webber',
    options: ['Mark Webber', 'Rubens Barrichello', 'Felipe Massa', 'Nico Rosberg'],
    context: "Webber's pointed dig at Red Bull after winning the 2010 British GP. Reports had emerged that the team had given Vettel newer, upgraded parts over him.",
    year: 2010,
    race: 'British GP',
  },
  {
    id: 'r06',
    quote: "Can I fight him, Rob? Can I fight him?",
    driver: 'Felipe Massa',
    options: ['Felipe Massa', 'Fernando Alonso', 'Rubens Barrichello', 'Michael Schumacher'],
    context: "Massa's desperate plea to engineer Rob Smedley seconds after hearing the infamous 'Fernando is faster than you' team order at the 2010 German GP. He was told to let his teammate through.",
    year: 2010,
    race: 'German GP',
  },
  {
    id: 'r07',
    quote: "I'm world champion! I'm world champion! Unbelievable!",
    driver: 'Nico Rosberg',
    options: ['Nico Rosberg', 'Lewis Hamilton', 'Sebastian Vettel', 'Valtteri Bottas'],
    context: "Rosberg's pure elation after finishing second in Abu Dhabi 2016 — enough to pip Hamilton to his one and only world title. He announced his retirement five days later.",
    year: 2016,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r08',
    quote: "That was the best race of my life! I can't believe it!",
    driver: 'Jenson Button',
    options: ['Jenson Button', 'Lewis Hamilton', 'Kimi Räikkönen', 'Sebastian Vettel'],
    context: "Button after the 2011 Canadian GP — widely considered one of F1's greatest races. He recovered from last place and a drive-through penalty to win in the final seconds.",
    year: 2011,
    race: 'Canadian GP',
  },
  {
    id: 'r09',
    quote: "I gave everything. Everything I had. I gave everything.",
    driver: 'Max Verstappen',
    options: ['Max Verstappen', 'Charles Leclerc', 'Lewis Hamilton', 'Sergio Pérez'],
    context: "Verstappen's gutted message after a hydraulics failure ended his race at the 2022 Azerbaijan GP while he was comfortably leading. One of several painful DNFs that year.",
    year: 2022,
    race: 'Azerbaijan GP',
  },
  {
    id: 'r10',
    quote: "I'm sorry, I'm sorry, I'm sorry. I destroyed the race for us.",
    driver: 'Charles Leclerc',
    options: ['Charles Leclerc', 'Carlos Sainz', 'Sebastian Vettel', 'Kimi Räikkönen'],
    context: "Leclerc's emotional apology to Ferrari after crashing in Monaco qualifying 2021, ending the session early and costing his rivals their final flying laps. He still started on pole.",
    year: 2021,
    race: 'Monaco GP',
  },
  {
    id: 'r11',
    quote: "This is my last lap in Formula 1. What a way to finish.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Sebastian Vettel', 'Fernando Alonso', 'Mark Webber'],
    context: "The Iceman's characteristically understated farewell on the final lap of Abu Dhabi 2021, ending a 21-year, 349-race F1 career. Delivered with the same calm he always had.",
    year: 2021,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r12',
    quote: "Understood. Understood. No, not understood.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Mark Webber', 'Nico Rosberg', 'Felipe Massa'],
    context: "Vettel's defiant radio reply to Red Bull's 'Multi 21' team order at Malaysia 2013 — instructing him to hold station behind Webber. He attacked and overtook to win, causing a major team fallout.",
    year: 2013,
    race: 'Malaysian GP',
  },
  {
    id: 'r13',
    quote: "I can't believe it! I can't believe it! YES! YES!",
    driver: 'Lando Norris',
    options: ['Lando Norris', 'Oscar Piastri', 'Carlos Sainz', 'George Russell'],
    context: "Norris's unbridled joy after winning the 2024 Miami GP — his maiden Formula 1 victory after years of near-misses and almost-moments. The wait was finally over.",
    year: 2024,
    race: 'Miami GP',
  },
  {
    id: 'r14',
    quote: "Bono, my tyres are gone. I'm really struggling, man.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Nico Rosberg', 'Valtteri Bottas', 'George Russell'],
    context: "Hamilton's trademark radio call to engineer Peter 'Bono' Bonnington became one of the most recognised phrases in modern F1 — and one of the internet's favourite memes.",
    year: 2017,
    race: 'Various',
  },
  {
    id: 'r15',
    quote: "This one's for you, Niki. This is for you.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Valtteri Bottas', 'Sebastian Vettel', 'Max Verstappen'],
    context: "Hamilton's touching tribute to Mercedes' Niki Lauda after winning the 2019 Monaco GP — just one week after Lauda's passing. One of the most emotional moments in recent F1 history.",
    year: 2019,
    race: 'Monaco GP',
  },
  {
    id: 'r16',
    quote: "I feel very old right now.",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Michael Schumacher', 'Kimi Räikkönen', 'Jenson Button'],
    context: "Alonso's weary message during his miserable second stint at McLaren, where Honda's chronic unreliability left the two-time world champion fighting at the back of the grid race after race.",
    year: 2015,
    race: 'Various',
  },
  {
    id: 'r17',
    quote: "YES! Come on! Come on! This is a great one! GREAT ONE!",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Fernando Alonso', 'Sebastian Vettel', 'Carlos Sainz'],
    context: "Even the Iceman melted at the 2018 US GP — his first win in five years. Räikkönen's uncharacteristic celebration had fans in Austin and around the world cheering right along with him.",
    year: 2018,
    race: 'US GP',
  },
  {
    id: 'r18',
    quote: "It's not going to work, is it. This is not going to work.",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Lewis Hamilton', 'Jenson Button', 'Nico Hülkenberg'],
    context: "Alonso's resigned acceptance as his McLaren-Honda continued to let him down in 2016. His dry, matter-of-fact delivery made it somehow more painful than shouting.",
    year: 2016,
    race: 'Various',
  },
  {
    id: 'r19',
    quote: "I love this team. I really, really love this team.",
    driver: 'Jenson Button',
    options: ['Jenson Button', 'Rubens Barrichello', 'Lewis Hamilton', 'Kimi Räikkönen'],
    context: "Button's affectionate message to Brawn GP after securing his world championship in 2009 — a team that had nearly gone under before producing the most dominant car of the season.",
    year: 2009,
    race: 'Brazilian GP',
  },
  {
    id: 'r20',
    quote: "In my mind I was always a Ferrari driver. I will always be.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Michael Schumacher', 'Kimi Räikkönen', 'Fernando Alonso'],
    context: "Vettel's emotional farewell after Ferrari chose not to renew his contract for 2021, ending a six-year partnership with the team he'd idolised since childhood. He wept on the radio.",
    year: 2020,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r21',
    quote: "This is so wrong! This is so wrong! I was ahead!",
    driver: 'Sergio Pérez',
    options: ['Sergio Pérez', 'Max Verstappen', 'Charles Leclerc', 'Carlos Sainz'],
    context: "Pérez's furious reaction after Red Bull's team orders handed Verstappen a position he was leading on track — the second time the same instruction was used that season.",
    year: 2023,
    race: 'Various',
  },
  {
    id: 'r22',
    quote: "Yeah yeah, I'm on it. Stop asking.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Max Verstappen', 'Sebastian Vettel', 'Carlos Sainz'],
    context: "Vintage Räikkönen — bluntly dismissing his engineer's repeated check-ins mid-race. The Iceman never needed reminding twice, or in this case, even once.",
    year: 2018,
    race: 'Various',
  },
  {
    id: 'r23',
    quote: "P1! On the hardest track in the world, P1!",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Ayrton Senna', 'Sebastian Vettel', 'Nico Rosberg'],
    context: "Hamilton's ecstatic call after clocking pole at Monaco — the circuit he considers the ultimate challenge for any driver. He has claimed pole there more times than anyone else.",
    year: 2019,
    race: 'Monaco GP',
  },
  {
    id: 'r24',
    quote: "Damage, damage, damage. I have damage. Mark it, mark it.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Nico Rosberg', 'Valtteri Bottas', 'George Russell'],
    context: "Hamilton's calm, precise damage report to the pit wall after contact during a race. His clinical composure under pressure — even when taking hits — was a hallmark of his championship years.",
    year: 2017,
    race: 'Various',
  },
  {
    id: 'r25',
    quote: "We are the champions! We are the champions! Come ON!",
    driver: 'Max Verstappen',
    options: ['Max Verstappen', 'Lewis Hamilton', 'Sebastian Vettel', 'Nico Rosberg'],
    context: "Verstappen's euphoric radio after clinching his maiden world championship at Abu Dhabi 2021 — ending Hamilton's bid for a record eighth title in the most controversial final lap in F1 history.",
    year: 2021,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r26',
    quote: "Thank you. Thank you for everything. This is goodbye.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Kimi Räikkönen', 'Fernando Alonso', 'Mark Webber'],
    context: "Vettel's heartfelt final radio message after the 2022 Abu Dhabi GP — his last Formula 1 race. He retired at 35, having won four world championships and 53 Grands Prix.",
    year: 2022,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r27',
    quote: "I'm not doing it! I'm not doing it! They can't ask me to do that!",
    driver: 'Mark Webber',
    options: ['Mark Webber', 'Rubens Barrichello', 'Felipe Massa', 'Valtteri Bottas'],
    context: "Webber's indignant refusal when Red Bull tried to enforce team orders during the 2013 season — frustration that had been building over years of feeling like the team's secondary driver.",
    year: 2013,
    race: 'Various',
  },
  {
    id: 'r28',
    quote: "Oh wow! Is this real? Is this real?! Oh my god!",
    driver: 'George Russell',
    options: ['George Russell', 'Lewis Hamilton', 'Valtteri Bottas', 'Lando Norris'],
    context: "Russell's disbelief after winning the 2022 Brazilian GP — his maiden Formula 1 victory, in only his second race for Mercedes. He barely let himself believe it until the chequered flag.",
    year: 2022,
    race: 'Brazilian GP',
  },
  {
    id: 'r29',
    quote: "This is for all the kids out there. Never, ever give up.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Valtteri Bottas', 'Sebastian Vettel', 'Charles Leclerc'],
    context: "Hamilton's characteristic post-win dedication message, reminding fans worldwide — especially young ones — of the values that drove him from a council estate to seven world championships.",
    year: 2020,
    race: 'Various',
  },
  {
    id: 'r30',
    quote: "I'm P1! I'm P1! First win! First win! Oh my god!",
    driver: 'Oscar Piastri',
    options: ['Oscar Piastri', 'Lando Norris', 'Carlos Sainz', 'George Russell'],
    context: "Piastri's first-ever Formula 1 victory — the 2024 Hungarian GP. The young Australian had been tipped for greatness since his junior career, and he finally delivered on all of it.",
    year: 2024,
    race: 'Hungarian GP',
  },
  {
    id: 'r31',
    quote: "This is the most difficult thing I have ever had to do in this sport. I'm sorry.",
    driver: 'Rubens Barrichello',
    options: ['Rubens Barrichello', 'Michael Schumacher', 'David Coulthard', 'Mika Häkkinen'],
    context: "Barrichello was ordered to slow down on the final straight of the 2002 Austrian GP, handing Schumacher a win he hadn't earned on the road. The crowd booed on the podium. One of F1's most controversial moments.",
    year: 2002,
    race: 'Austrian GP',
  },
  {
    id: 'r32',
    quote: "YEAH BABY! YEAH BABY! YEAH BABY! I love you guys! YEAH BABY!",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Lewis Hamilton', 'Mark Webber', 'Kimi Räikkönen'],
    context: "Vettel's signature celebration chant became one of F1's most recognisable radio calls during his dominant 2011–2013 era. Win after win, the 'Yeah baby' never got old — for him, at least.",
    year: 2013,
    race: 'Various',
  },
  {
    id: 'r33',
    quote: "Yes! Yes! YES! First win! First win! Oh my god! Oh my god!",
    driver: 'Valtteri Bottas',
    options: ['Valtteri Bottas', 'Lewis Hamilton', 'Kimi Räikkönen', 'Daniel Ricciardo'],
    context: "Bottas finally broke his win duck at the 2017 Russian GP after years of near-misses in his career. Pure, unfiltered joy from a driver who had worked quietly and patiently for this moment.",
    year: 2017,
    race: 'Russian GP',
  },
  {
    id: 'r34',
    quote: "Seven! Bono, SEVEN! That's seven!",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Max Verstappen', 'Valtteri Bottas', 'Sebastian Vettel'],
    context: "Hamilton's disbelieving call after clinching his seventh world championship at the 2020 Turkish GP — equalling Michael Schumacher's all-time record. Delivered in the rain, in one of the cleanest drives of his career.",
    year: 2020,
    race: 'Turkish GP',
  },
  {
    id: 'r35',
    quote: "I did it! I'm world champion! YES! I DID IT!",
    driver: 'Damon Hill',
    options: ['Damon Hill', 'Michael Schumacher', 'Jacques Villeneuve', 'Mika Häkkinen'],
    context: "Hill's emotional outburst after clinching the 1996 world championship at Suzuka — the son of two-time champion Graham Hill finally following in his father's footsteps, two decades later.",
    year: 1996,
    race: 'Japanese GP',
  },
  {
    id: 'r36',
    quote: "For the tifosi! This is for the tifosi! MONZA! YES!",
    driver: 'Charles Leclerc',
    options: ['Charles Leclerc', 'Sebastian Vettel', 'Lewis Hamilton', 'Kimi Räikkönen'],
    context: "Leclerc won back-to-back races at Spa and Monza in 2019, dedicating the Italian GP to Ferrari's fans — and to Anthoine Hubert, whose fatal accident at Spa had occurred just a week before.",
    year: 2019,
    race: 'Italian GP',
  },
  {
    id: 'r37',
    quote: "Yeah... I think that's it. We've done it.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Lewis Hamilton', 'Fernando Alonso', 'Felipe Massa'],
    context: "Räikkönen came into the 2007 Brazilian GP third in the championship and left as world champion — a stunning reversal of fortune. His reaction was, of course, perfectly understated.",
    year: 2007,
    race: 'Brazilian GP',
  },
  {
    id: 'r38',
    quote: "SHOEY! We're doing a shoey! GET IN! SHOEY TIME!",
    driver: 'Daniel Ricciardo',
    options: ['Daniel Ricciardo', 'Max Verstappen', 'Sebastian Vettel', 'Carlos Sainz'],
    context: "Ricciardo's tradition of drinking champagne from his sweaty racing boot on the podium became one of F1's most beloved rituals. Even Kimi Räikkönen reluctantly joined in at the 2018 US GP.",
    year: 2016,
    race: 'Various',
  },
  {
    id: 'r39',
    quote: "What happened?! What HAPPENED?! I had the win! I had Monaco!",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Max Verstappen', 'Charles Leclerc', 'Carlos Sainz'],
    context: "Alonso was set for a fairytale Monaco win in 2023 with Aston Martin when a miscommunication during a pit stop cost him the lead. He finished second. A win Monaco still owes him.",
    year: 2023,
    race: 'Monaco GP',
  },
  {
    id: 'r40',
    quote: "FOUR! Four world championships! How is this even possible?!",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Lewis Hamilton', 'Fernando Alonso', 'Kimi Räikkönen'],
    context: "Vettel's incredulous reaction after securing his fourth consecutive world championship at the 2013 Japanese GP. He went on to win nine of the final ten races that season.",
    year: 2013,
    race: 'Japanese GP',
  },
  {
    id: 'r41',
    quote: "To whom it may concern — f*** you.",
    driver: 'Valtteri Bottas',
    options: ['Valtteri Bottas', 'Lewis Hamilton', 'Kimi Räikkönen', 'Max Verstappen'],
    context: "Bottas opened the 2019 season with a dominant win in Australia, delivering this message to every doubter after a difficult 2018. It became his battle cry for the year.",
    year: 2019,
    race: 'Australian GP',
  },
  {
    id: 'r42',
    quote: "MONACO! I won in MONACO! Carlos Sainz won in Monaco! Are you serious?!",
    driver: 'Carlos Sainz',
    options: ['Carlos Sainz', 'Charles Leclerc', 'Max Verstappen', 'Lando Norris'],
    context: "Sainz won the 2024 Monaco GP against the odds — on his way out of Ferrari and in a season dominated by Verstappen. One of the most satisfying personal victories in recent F1 memory.",
    year: 2024,
    race: 'Monaco GP',
  },
  {
    id: 'r43',
    quote: "I won! I actually won a Formula 1 race! This is not real! MONZA!",
    driver: 'Pierre Gasly',
    options: ['Pierre Gasly', 'Lewis Hamilton', 'Lando Norris', 'Charles Leclerc'],
    context: "Gasly's shock win at the 2020 Italian GP with AlphaTauri — after a Safety Car and Hamilton's pit lane penalty — was one of F1's biggest upsets. He had been demoted from Red Bull less than a year earlier.",
    year: 2020,
    race: 'Italian GP',
  },
  {
    id: 'r44',
    quote: "I am the world champion! I AM THE WORLD CHAMPION!",
    driver: 'Mika Häkkinen',
    options: ['Mika Häkkinen', 'Michael Schumacher', 'David Coulthard', 'Rubens Barrichello'],
    context: "Häkkinen's pure joy after winning his first world championship at the 1998 Japanese GP — three years after surviving a life-threatening head injury at the 1995 Australian GP.",
    year: 1998,
    race: 'Japanese GP',
  },
  {
    id: 'r45',
    quote: "I want to dedicate this win to the Black community. You all matter so much.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Valtteri Bottas', 'Max Verstappen', 'Charles Leclerc'],
    context: "Hamilton used his 2020 Styrian GP victory to spotlight the Black Lives Matter movement, arriving at the race in an all-black car and wearing a dedicated T-shirt on the podium. He spoke with characteristic directness.",
    year: 2020,
    race: 'Styrian GP',
  },
  {
    id: 'r46',
    quote: "I know I shouldn't have done that. I owe Mark an apology. I'm sorry.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Mark Webber', 'Fernando Alonso', 'Lewis Hamilton'],
    context: "Vettel's post-race admission after ignoring Red Bull's 'Multi 21' team order in Malaysia 2013. The apology was delivered sincerely but the damage to his relationship with Webber was already done.",
    year: 2013,
    race: 'Malaysian GP',
  },
  {
    id: 'r47',
    quote: "I'm a racing driver. This is what I do. I race. End of story.",
    driver: 'Max Verstappen',
    options: ['Max Verstappen', 'Lewis Hamilton', 'Sergio Pérez', 'Charles Leclerc'],
    context: "Verstappen's defiant response when questioned about his aggressive driving style during the brutal 2021 title fight with Hamilton. His refusal to back down defined one of F1's most intense championships.",
    year: 2021,
    race: 'Various',
  },
  {
    id: 'r48',
    quote: "This car is incredible! These tyres feel incredible! We can fight everyone!",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Lance Stroll', 'Carlos Sainz', 'George Russell'],
    context: "Alonso's delight after discovering Aston Martin's 2023 challenger was genuinely competitive — a world away from the Honda-powered McLarens he'd suffered through. He turned 41 mid-season and was faster than ever.",
    year: 2023,
    race: 'Bahrain GP',
  },
  {
    id: 'r49',
    quote: "I don't know what to say. I genuinely don't know what to say.",
    driver: 'Lando Norris',
    options: ['Lando Norris', 'Oscar Piastri', 'George Russell', 'Carlos Sainz'],
    context: "Norris in the closing laps of his first Formula 1 victory at the 2024 Miami GP, finally at a loss for words after years of near-misses. His usual match-winning commentary had gone quiet — replaced by something rarer.",
    year: 2024,
    race: 'Miami GP',
  },
  {
    id: 'r50',
    quote: "This is it. Last race. Thank you all for an unbelievable journey. Truly.",
    driver: 'Mark Webber',
    options: ['Mark Webber', 'Sebastian Vettel', 'Fernando Alonso', 'Kimi Räikkönen'],
    context: "Webber's farewell on the final lap of the 2013 Brazilian GP — his last Formula 1 race. He retired to pursue a career in endurance racing, leaving F1 as one of its most respected and straight-talking competitors.",
    year: 2013,
    race: 'Brazilian GP',
  },
  {
    id: 'r51',
    quote: "We did it. We finally did it. This one's for Papa.",
    driver: 'Charles Leclerc',
    options: ['Charles Leclerc', 'Carlos Sainz', 'Lando Norris', 'Max Verstappen'],
    context: "Leclerc finally won his home race at the 2024 Monaco GP — a circuit that had broken his heart year after year. He dedicated the emotional victory to his late father, Hervé, who passed away in 2017.",
    year: 2024,
    race: 'Monaco GP',
  },
  {
    id: 'r52',
    quote: "We did it! We won Monaco! I had no power for most of that race!",
    driver: 'Daniel Ricciardo',
    options: ['Daniel Ricciardo', 'Max Verstappen', 'Sebastian Vettel', 'Lewis Hamilton'],
    context: "Ricciardo won the 2018 Monaco GP despite an MGU-K failure that cost him around 25% of his engine's power from a third of the way in. He nursed the wounded Red Bull home for one of the great defensive drives.",
    year: 2018,
    race: 'Monaco GP',
  },
  {
    id: 'r53',
    quote: "Yes! Get in there! This is the greatest day of my life!",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Nico Rosberg', 'Jenson Button', 'Sebastian Vettel'],
    context: "Hamilton's elation after winning the 2014 Abu Dhabi GP finale to claim his second world title — and his first with Mercedes, beating teammate Nico Rosberg in the double-points decider.",
    year: 2014,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r54',
    quote: "Vamos! Come on! What a win for the whole team!",
    driver: 'Sergio Pérez',
    options: ['Sergio Pérez', 'Max Verstappen', 'Carlos Sainz', 'Charles Leclerc'],
    context: "Pérez took his first win for Red Bull at the chaotic 2021 Azerbaijan GP, inheriting the lead after Verstappen's late tyre blowout and holding on through the red-flag restart in Baku.",
    year: 2021,
    race: 'Azerbaijan GP',
  },
  {
    id: 'r55',
    quote: "I won! My first win! I can't believe it!",
    driver: 'Esteban Ocon',
    options: ['Esteban Ocon', 'Pierre Gasly', 'Fernando Alonso', 'Sebastian Vettel'],
    context: "Ocon's maiden Formula 1 victory came at the 2021 Hungarian GP after first-lap chaos reshuffled the grid. He held off Vettel (later disqualified) for the entire race in the Alpine.",
    year: 2021,
    race: 'Hungarian GP',
  },
  {
    id: 'r56',
    quote: "Simply lovely.",
    driver: 'Max Verstappen',
    options: ['Max Verstappen', 'Daniel Ricciardo', 'Sergio Pérez', 'Lando Norris'],
    context: "Verstappen's understated, deadpan praise of his car over the radio became an instant fan-favourite catchphrase — the calm flip side to his more fiery transmissions.",
    year: 2021,
    race: 'Various',
  },
  {
    id: 'r57',
    quote: "Suck my balls, mate.",
    driver: 'Kevin Magnussen',
    options: ['Kevin Magnussen', 'Nico Hülkenberg', 'Romain Grosjean', 'Daniil Kvyat'],
    context: "Magnussen's blunt response after Nico Hülkenberg confronted him about his aggressive driving at the 2017 Hungarian GP. The exchange became one of F1's most quoted radio moments.",
    year: 2017,
    race: 'Hungarian GP',
  },
  {
    id: 'r58',
    quote: "I'm the world champion! I can't believe it!",
    driver: 'Jacques Villeneuve',
    options: ['Jacques Villeneuve', 'Michael Schumacher', 'Damon Hill', 'Mika Häkkinen'],
    context: "Villeneuve clinched the 1997 title at the European GP in Jerez after Schumacher's infamous attempt to take him out backfired — the Ferrari beached in the gravel while Villeneuve carried on to third.",
    year: 1997,
    race: 'European GP',
  },
  {
    id: 'r59',
    quote: "Thank you, guys. Thank you so much. We did it together.",
    driver: 'Michael Schumacher',
    options: ['Michael Schumacher', 'Mika Häkkinen', 'Rubens Barrichello', 'David Coulthard'],
    context: "Schumacher wept on the radio after winning the 2000 Japanese GP to take his first title with Ferrari — ending the team's 21-year wait for a drivers' world championship.",
    year: 2000,
    race: 'Japanese GP',
  },
  {
    id: 'r60',
    quote: "P1! We won! Come on, Williams!",
    driver: 'Pastor Maldonado',
    options: ['Pastor Maldonado', 'Fernando Alonso', 'Kimi Räikkönen', 'Felipe Massa'],
    context: "Maldonado's stunning win at the 2012 Spanish GP was his only Formula 1 victory — and Williams's first since 2004. He converted pole into a controlled drive that nobody saw coming.",
    year: 2012,
    race: 'Spanish GP',
  },
]
