export interface RadioQuote {
  id: string
  quote: string
  driver: string
  options: [string, string, string, string]
  context: string
  year: number
  race: string
}

// options[0] is always the correct driver — shuffle in the component
export const RADIO_QUOTES: RadioQuote[] = [
  {
    id: 'r01',
    quote: "Leave me alone, I know what I'm doing.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Sebastian Vettel', 'Fernando Alonso', 'Lewis Hamilton'],
    context: "Räikkönen's engineer kept giving him gap updates during the 2012 Abu Dhabi GP. Kimi had it completely under control — and won the race.",
    year: 2012,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r02',
    quote: "GP2 engine! GP2 engine! Argh!",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Jenson Button', 'Romain Grosjean', 'Kevin Magnussen'],
    context: "Alonso's legendary explosion of frustration at the 2015 Malaysian GP after being lapped. McLaren's Honda engine was producing GP2-level power — in an F1 car.",
    year: 2015,
    race: 'Malaysian GP',
  },
  {
    id: 'r03',
    quote: "I am the world champion! I am the world champion! Oh my god!",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Mark Webber', 'Fernando Alonso', 'Jenson Button'],
    context: "Vettel's raw, barely-believing reaction when he clinched his first of four consecutive championships at the 2010 Japanese GP. He was just 23 years old.",
    year: 2010,
    race: 'Japanese GP',
  },
  {
    id: 'r04',
    quote: "Oh my god, I'm world champion!",
    driver: 'Jenson Button',
    options: ['Jenson Button', 'Rubens Barrichello', 'Lewis Hamilton', 'Kimi Räikkönen'],
    context: "Button's shocked joy after winning the 2009 Brazilian GP, sealing his only world title with the Brawn GP team — a near-bankrupt outfit that came from nowhere.",
    year: 2009,
    race: 'Brazilian GP',
  },
  {
    id: 'r05',
    quote: "Not bad for a number two driver.",
    driver: 'Mark Webber',
    options: ['Mark Webber', 'Rubens Barrichello', 'Felipe Massa', 'Nico Rosberg'],
    context: "Webber's pointed dig at Red Bull after winning the 2010 British GP. Reports had emerged that the team had given Vettel newer, upgraded parts over him.",
    year: 2010,
    race: 'British GP',
  },
  {
    id: 'r06',
    quote: "Can I fight him, Rob? Can I fight him?",
    driver: 'Felipe Massa',
    options: ['Felipe Massa', 'Fernando Alonso', 'Rubens Barrichello', 'Michael Schumacher'],
    context: "Massa's desperate plea to engineer Rob Smedley seconds after hearing the infamous 'Fernando is faster than you' team order at the 2010 German GP. He was told to let his teammate through.",
    year: 2010,
    race: 'German GP',
  },
  {
    id: 'r07',
    quote: "I'm world champion! I'm world champion! Unbelievable!",
    driver: 'Nico Rosberg',
    options: ['Nico Rosberg', 'Lewis Hamilton', 'Sebastian Vettel', 'Valtteri Bottas'],
    context: "Rosberg's pure elation after finishing second in Abu Dhabi 2016 — enough to pip Hamilton to his one and only world title. He announced his retirement five days later.",
    year: 2016,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r08',
    quote: "That was the best race of my life! I can't believe it!",
    driver: 'Jenson Button',
    options: ['Jenson Button', 'Lewis Hamilton', 'Kimi Räikkönen', 'Sebastian Vettel'],
    context: "Button after the 2011 Canadian GP — widely considered one of F1's greatest races. He recovered from last place and a drive-through penalty to win in the final seconds.",
    year: 2011,
    race: 'Canadian GP',
  },
  {
    id: 'r09',
    quote: "I gave everything. Everything I had. I gave everything.",
    driver: 'Max Verstappen',
    options: ['Max Verstappen', 'Charles Leclerc', 'Lewis Hamilton', 'Sergio Pérez'],
    context: "Verstappen's gutted message after a hydraulics failure ended his race at the 2022 Azerbaijan GP while he was comfortably leading. One of several painful DNFs that year.",
    year: 2022,
    race: 'Azerbaijan GP',
  },
  {
    id: 'r10',
    quote: "I'm sorry, I'm sorry, I'm sorry. I destroyed the race for us.",
    driver: 'Charles Leclerc',
    options: ['Charles Leclerc', 'Carlos Sainz', 'Sebastian Vettel', 'Kimi Räikkönen'],
    context: "Leclerc's emotional apology to Ferrari after crashing in Monaco qualifying 2021, ending the session early and costing his rivals their final flying laps. He still started on pole.",
    year: 2021,
    race: 'Monaco GP',
  },
  {
    id: 'r11',
    quote: "This is my last lap in Formula 1. What a way to finish.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Sebastian Vettel', 'Fernando Alonso', 'Mark Webber'],
    context: "The Iceman's characteristically understated farewell on the final lap of Abu Dhabi 2021, ending a 21-year, 349-race F1 career. Delivered with the same calm he always had.",
    year: 2021,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r12',
    quote: "Understood. Understood. No, not understood.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Mark Webber', 'Nico Rosberg', 'Felipe Massa'],
    context: "Vettel's defiant radio reply to Red Bull's 'Multi 21' team order at Malaysia 2013 — instructing him to hold station behind Webber. He attacked and overtook to win, causing a major team fallout.",
    year: 2013,
    race: 'Malaysian GP',
  },
  {
    id: 'r13',
    quote: "I can't believe it! I can't believe it! YES! YES!",
    driver: 'Lando Norris',
    options: ['Lando Norris', 'Oscar Piastri', 'Carlos Sainz', 'George Russell'],
    context: "Norris's unbridled joy after winning the 2024 Miami GP — his maiden Formula 1 victory after years of near-misses and almost-moments. The wait was finally over.",
    year: 2024,
    race: 'Miami GP',
  },
  {
    id: 'r14',
    quote: "Bono, my tyres are gone. I'm really struggling, man.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Nico Rosberg', 'Valtteri Bottas', 'George Russell'],
    context: "Hamilton's trademark radio call to engineer Peter 'Bono' Bonnington became one of the most recognised phrases in modern F1 — and one of the internet's favourite memes.",
    year: 2017,
    race: 'Various',
  },
  {
    id: 'r15',
    quote: "This one's for you, Niki. This is for you.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Valtteri Bottas', 'Sebastian Vettel', 'Max Verstappen'],
    context: "Hamilton's touching tribute to Mercedes' Niki Lauda after winning the 2019 Monaco GP — just one week after Lauda's passing. One of the most emotional moments in recent F1 history.",
    year: 2019,
    race: 'Monaco GP',
  },
  {
    id: 'r16',
    quote: "I feel very old right now.",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Michael Schumacher', 'Kimi Räikkönen', 'Jenson Button'],
    context: "Alonso's weary message during his miserable second stint at McLaren, where Honda's chronic unreliability left the two-time world champion fighting at the back of the grid race after race.",
    year: 2015,
    race: 'Various',
  },
  {
    id: 'r17',
    quote: "YES! Come on! Come on! This is a great one! GREAT ONE!",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Fernando Alonso', 'Sebastian Vettel', 'Carlos Sainz'],
    context: "Even the Iceman melted at the 2018 US GP — his first win in five years. Räikkönen's uncharacteristic celebration had fans in Austin and around the world cheering right along with him.",
    year: 2018,
    race: 'US GP',
  },
  {
    id: 'r18',
    quote: "It's not going to work, is it. This is not going to work.",
    driver: 'Fernando Alonso',
    options: ['Fernando Alonso', 'Lewis Hamilton', 'Jenson Button', 'Nico Hülkenberg'],
    context: "Alonso's resigned acceptance as his McLaren-Honda continued to let him down in 2016. His dry, matter-of-fact delivery made it somehow more painful than shouting.",
    year: 2016,
    race: 'Various',
  },
  {
    id: 'r19',
    quote: "I love this team. I really, really love this team.",
    driver: 'Jenson Button',
    options: ['Jenson Button', 'Rubens Barrichello', 'Lewis Hamilton', 'Kimi Räikkönen'],
    context: "Button's affectionate message to Brawn GP after securing his world championship in 2009 — a team that had nearly gone under before producing the most dominant car of the season.",
    year: 2009,
    race: 'Brazilian GP',
  },
  {
    id: 'r20',
    quote: "In my mind I was always a Ferrari driver. I will always be.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Michael Schumacher', 'Kimi Räikkönen', 'Fernando Alonso'],
    context: "Vettel's emotional farewell after Ferrari chose not to renew his contract for 2021, ending a six-year partnership with the team he'd idolised since childhood. He wept on the radio.",
    year: 2020,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r21',
    quote: "This is so wrong! This is so wrong! I was ahead!",
    driver: 'Sergio Pérez',
    options: ['Sergio Pérez', 'Max Verstappen', 'Charles Leclerc', 'Carlos Sainz'],
    context: "Pérez's furious reaction after Red Bull's team orders handed Verstappen a position he was leading on track — the second time the same instruction was used that season.",
    year: 2023,
    race: 'Various',
  },
  {
    id: 'r22',
    quote: "Yeah yeah, I'm on it. Stop asking.",
    driver: 'Kimi Räikkönen',
    options: ['Kimi Räikkönen', 'Max Verstappen', 'Sebastian Vettel', 'Carlos Sainz'],
    context: "Vintage Räikkönen — bluntly dismissing his engineer's repeated check-ins mid-race. The Iceman never needed reminding twice, or in this case, even once.",
    year: 2018,
    race: 'Various',
  },
  {
    id: 'r23',
    quote: "P1! On the hardest track in the world, P1!",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Ayrton Senna', 'Sebastian Vettel', 'Nico Rosberg'],
    context: "Hamilton's ecstatic call after clocking pole at Monaco — the circuit he considers the ultimate challenge for any driver. He has claimed pole there more times than anyone else.",
    year: 2019,
    race: 'Monaco GP',
  },
  {
    id: 'r24',
    quote: "Damage, damage, damage. I have damage. Mark it, mark it.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Nico Rosberg', 'Valtteri Bottas', 'George Russell'],
    context: "Hamilton's calm, precise damage report to the pit wall after contact during a race. His clinical composure under pressure — even when taking hits — was a hallmark of his championship years.",
    year: 2017,
    race: 'Various',
  },
  {
    id: 'r25',
    quote: "We are the champions! We are the champions! Come ON!",
    driver: 'Max Verstappen',
    options: ['Max Verstappen', 'Lewis Hamilton', 'Sebastian Vettel', 'Nico Rosberg'],
    context: "Verstappen's euphoric radio after clinching his maiden world championship at Abu Dhabi 2021 — ending Hamilton's bid for a record eighth title in the most controversial final lap in F1 history.",
    year: 2021,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r26',
    quote: "Thank you. Thank you for everything. This is goodbye.",
    driver: 'Sebastian Vettel',
    options: ['Sebastian Vettel', 'Kimi Räikkönen', 'Fernando Alonso', 'Mark Webber'],
    context: "Vettel's heartfelt final radio message after the 2022 Abu Dhabi GP — his last Formula 1 race. He retired at 35, having won four world championships and 53 Grands Prix.",
    year: 2022,
    race: 'Abu Dhabi GP',
  },
  {
    id: 'r27',
    quote: "I'm not doing it! I'm not doing it! They can't ask me to do that!",
    driver: 'Mark Webber',
    options: ['Mark Webber', 'Rubens Barrichello', 'Felipe Massa', 'Valtteri Bottas'],
    context: "Webber's indignant refusal when Red Bull tried to enforce team orders during the 2013 season — frustration that had been building over years of feeling like the team's secondary driver.",
    year: 2013,
    race: 'Various',
  },
  {
    id: 'r28',
    quote: "Oh wow! Is this real? Is this real?! Oh my god!",
    driver: 'George Russell',
    options: ['George Russell', 'Lewis Hamilton', 'Valtteri Bottas', 'Lando Norris'],
    context: "Russell's disbelief after winning the 2022 Brazilian GP — his maiden Formula 1 victory, in only his second race for Mercedes. He barely let himself believe it until the chequered flag.",
    year: 2022,
    race: 'Brazilian GP',
  },
  {
    id: 'r29',
    quote: "This is for all the kids out there. Never, ever give up.",
    driver: 'Lewis Hamilton',
    options: ['Lewis Hamilton', 'Valtteri Bottas', 'Sebastian Vettel', 'Charles Leclerc'],
    context: "Hamilton's characteristic post-win dedication message, reminding fans worldwide — especially young ones — of the values that drove him from a council estate to seven world championships.",
    year: 2020,
    race: 'Various',
  },
  {
    id: 'r30',
    quote: "I'm P1! I'm P1! First win! First win! Oh my god!",
    driver: 'Oscar Piastri',
    options: ['Oscar Piastri', 'Lando Norris', 'Carlos Sainz', 'George Russell'],
    context: "Piastri's first-ever Formula 1 victory — the 2024 Hungarian GP. The young Australian had been tipped for greatness since his junior career, and he finally delivered on all of it.",
    year: 2024,
    race: 'Hungarian GP',
  },
]
