import type { Metadata } from 'next'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and conditions for using F1RaceSignature — the Formula 1 telemetry poster art tool.',
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms & Conditions | F1RaceSignature',
    description: 'Terms and conditions for using F1RaceSignature.',
    url: '/terms',
    type: 'website',
  },
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xs font-mono uppercase tracking-widest text-white/45 mb-4">{title}</h2>
      <div className="space-y-3 text-white/65 leading-relaxed">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="pt-14 min-h-screen" style={{ background: '#030303' }}>
        {/* Hero */}
        <div className="border-b border-[#0f0f0f] py-16 px-6 text-center">
          <p className="text-white/50 text-xs font-mono uppercase tracking-widest mb-4">Legal</p>
          <h1
            className="text-4xl md:text-5xl text-white mb-4"
            style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}
          >
            Terms &amp; Conditions
          </h1>
          <p className="text-white/50 text-sm">Last updated: June 2026</p>
        </div>

        <div className="max-w-3xl mx-auto px-6 py-16 space-y-12">

          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using F1RaceSignature (&quot;the Service&quot;), you agree to be bound by
              these Terms &amp; Conditions. If you do not agree to these terms, please do not use the
              Service.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              F1RaceSignature is a free, browser-based creative tool that transforms publicly available
              Formula 1 telemetry data into poster artwork. The Service requires no account or
              registration to use.
            </p>
          </Section>

          <Section title="3. Intellectual Property & Disclaimer">
            <p>
              F1RaceSignature is an independent fan project. It is not affiliated with, endorsed by, or
              connected to Formula 1, Formula One Management Limited, the FIA, or any Formula 1 team or
              driver.
            </p>
            <p>
              All Formula 1 team names, driver names, circuit names, and related marks are the property
              of their respective owners. Their use on this platform is strictly for informational and
              artistic reference purposes.
            </p>
            <p>
              The telemetry data underlying the visualizations is sourced from the official F1
              live-timing feed via the open-source FastF1 library and is used for artistic and
              educational purposes only.
            </p>
          </Section>

          <Section title="4. Permitted Use">
            <p>You may use the Service to:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Create poster artwork for personal, non-commercial use.</li>
              <li>Share exported posters on personal social media accounts, provided you credit F1RaceSignature.</li>
              <li>Print exported posters for personal display in your home.</li>
            </ul>
          </Section>

          <Section title="5. Prohibited Use">
            <p>You may not:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Sell, license, or commercially distribute any exported poster or artwork generated by the Service.</li>
              <li>Use the Service or its outputs to create merchandise for sale without prior written permission.</li>
              <li>Attempt to reverse-engineer, scrape, or extract telemetry data from the Service at scale.</li>
              <li>Use the Service for any unlawful purpose or in a manner that violates any applicable laws.</li>
              <li>Misrepresent exported artwork as officially licensed Formula 1 merchandise.</li>
            </ul>
          </Section>

          <Section title="6. User-Generated Exports">
            <p>
              Posters you export are generated entirely in your browser. We do not store, review, or
              claim ownership over any poster you create. You are responsible for how you use and
              distribute any exported files.
            </p>
          </Section>

          <Section title="7. Premium Features">
            <p>
              Certain features of the Service (additional visualization modes, themes, and export
              formats) may be made available in the future as part of a paid tier. Any pricing and
              payment terms will be clearly communicated before purchase.
            </p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
              express or implied. F1RaceSignature shall not be liable for any indirect, incidental,
              special, or consequential damages arising out of or in connection with your use of the
              Service.
            </p>
            <p>
              We do not guarantee the accuracy, completeness, or timeliness of any telemetry data or
              race results displayed.
            </p>
          </Section>

          <Section title="9. Changes to Terms">
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the Service
              after any changes constitutes your acceptance of the revised Terms. The &quot;last updated&quot;
              date at the top of this page will reflect any changes.
            </p>
          </Section>

          <Section title="10. Contact">
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:wayfarerwondersblog@gmail.com" className="text-[#d4a017] hover:underline">
                wayfarerwondersblog@gmail.com
              </a>
              .
            </p>
          </Section>

        </div>
      </main>
      <Footer />
    </>
  )
}
