export interface DriverCareer {
  driverId: string
  career: string[]
}

export const DRIVER_CAREERS: DriverCareer[] = [
  {
    driverId: 'hamilton',
    career: [
      'Lewis Hamilton arrived in Formula 1 in 2007 as the most hyped rookie in the sport\'s history, and he immediately justified it. In his debut season at McLaren he pushed world champion Fernando Alonso to a third-place finish in the championship — as a first-year driver — and came within a single point of winning the title. It was an entrance unlike any other, and it announced not just a driver of exceptional talent but one who appeared immune to pressure at the highest level.',
      'His first world championship came in 2008 in the most dramatic fashion possible: on the final corner of the final lap of the final race in Brazil. Hamilton overtook Timo Glock in the wet at Interlagos to take the fifth place he needed to claim the title by a single point from Felipe Massa. It was a conclusion so cinematic that it defined the early image of Hamilton as a driver who seemed destined to be at the centre of Formula 1\'s greatest moments.',
      'The years with Mercedes from 2013 onward transformed Hamilton from a very good Formula 1 champion into the statistical greatest of all time. Six more titles between 2014 and 2020, including a 2019 and 2020 run so dominant that his records for most wins and most pole positions became essentially unreachable for any current driver. His 2020 season — 11 wins from 17 races in a shortened pandemic campaign — was the most authoritative individual performance in the hybrid era.',
      'In 2026, Hamilton made the move that the paddock had speculated about for years, joining Ferrari for the final chapter of his career. His first win in scarlet came at the Barcelona Grand Prix, a controlled, imperious display that showed a seven-time champion still operating at the front of the sport. The move to Ferrari gave a great career its most romantic ending: the greatest driver of his generation, in the most famous red car in motorsport history.',
    ],
  },
  {
    driverId: 'verstappen',
    career: [
      'Max Verstappen became the youngest Formula 1 race winner in history when he won the 2016 Spanish Grand Prix on his debut for Red Bull Racing at the age of 18 years and 228 days. The win was not a fluke — he passed Kimi Räikkönen\'s Ferrari in the closing stages with the assurance of a driver twice his age. Formula 1 had seen prodigies before, but the manner of Verstappen\'s arrival suggested something qualitatively different: not just a fast young driver, but one who appeared to have skipped the learning phase entirely.',
      'His path to the 2021 World Championship was the most contested in the hybrid era. Through 22 races, he and Lewis Hamilton traded victories and collisions — Silverstone, Monza, Saudi Arabia — in a season that raised every question Formula 1 asks about the boundary between racing and foul play. The title was decided at Abu Dhabi on the final lap under circumstances so controversial that they prompted a fundamental restructuring of how the sport manages its race direction.',
      'What followed was even more emphatic. In 2022, Verstappen won 15 of 22 races, clinching the championship with four races remaining. In 2023, he won 19 races — a record that seemed impossible until he did it. By 2024, he had four consecutive world championships and had already established himself in the conversation about the greatest Formula 1 driver of all time, a conversation that would have seemed absurd to even broach about any driver at 27 years old.',
      'Verstappen\'s driving style combines raw pace with an almost preternatural ability to manage tyres, manage traffic, and extract performance from a car across a full race distance. His overtaking ability — particularly late-braking moves into tight corners — is as aggressive as any driver in the sport\'s history, and his wheel-to-wheel racecraft recalls Michael Schumacher in its absolute refusal to yield without a fight.',
    ],
  },
  {
    driverId: 'schumacher',
    career: [
      'Michael Schumacher\'s career begins not with his first race win but with his first lap in a Formula 1 car at the 1991 Belgian Grand Prix. Without a testing contract and having barely driven a Formula 1 car before the race weekend, Schumacher qualified seventh at Spa-Francorchamps — one of the most technically demanding circuits on the calendar. The performance earned him a full seat immediately. It was a debut that announced a talent of a different order.',
      'His first world championship came in 1994 in circumstances shadowed by tragedy. Ayrton Senna died at Imola. Roland Ratzenberger died the day before. The season became something darker than a championship contest. Schumacher won the title at the final race in Adelaide in an incident with Damon Hill that has never been definitively adjudicated — racing accident or deliberate foul? The ambiguity surrounded him through the decade.',
      'The Ferrari years from 2000 to 2004 represent the most sustained period of individual dominance in Formula 1 history. Five consecutive world championships. 72 race victories in a Ferrari before he retired the first time in 2006. A working partnership with technical director Ross Brawn and team principal Jean Todt that rebuilt Ferrari from a team that had not won a championship in 21 years into the most formidable operation in the sport. His 2004 season — 13 wins from the first 14 races — remains perhaps the most statistically dominant single campaign in the hybrid-era or pre-hybrid era.',
      'Schumacher\'s legacy extends beyond his records. He professionalised Formula 1 driver preparation — his physical fitness and nutrition regime set the standard that the entire paddock has followed since. He shaped the development of his Ferrari cars through engineering feedback of unusual quality, contributing directly to the car\'s development in ways most drivers cannot. His tragic skiing accident in 2013 and the years that followed gave his story a dimension of loss that his career alone did not carry.',
    ],
  },
  {
    driverId: 'senna',
    career: [
      'Ayrton Senna came from São Paulo to Europe in the early 1980s with nothing except an absolute, unwavering certainty that he would become Formula 1 world champion. He drove in Formula Ford, Formula Three, and then Formula 1 with the Toleman team in 1984, and at every level the story was the same: other drivers were very fast, and Senna was something else. His qualifying lap at Monaco in 1984 — in a Toleman that should not have been at the front of the grid — is still cited as evidence that he was operating in a different register from everyone around him.',
      'His years at McLaren Honda from 1988 to 1993 produced three world championships and some of the most spectacular individual performances in the sport\'s history. The 1988 season was a complete statement of dominance — 15 wins from 16 races between Senna and Prost, a combination so superior to the rest of the grid that the competition barely existed. Within that, Senna\'s eight race victories included performances at Monaco and in difficult conditions that nobody around him was producing.',
      'His rivalry with Alain Prost became the defining narrative of late-1980s Formula 1 — two drivers of utterly different temperaments competing for the same world championships in the same car. The relationship deteriorated into open hostility. The collisions at Suzuka in 1989 and 1990, both of which decided championships, raised questions about the boundary between racing and deliberate interference that followed both drivers for the rest of their careers.',
      'Senna died at Imola on 1 May 1994, at the age of 34, during the San Marino Grand Prix. His death transformed Formula 1 more thoroughly than any single event before or since — it prompted an almost total overhaul of circuit safety standards that have saved countless lives in the thirty years since. He remains the driver that most Formula 1 fans cite, regardless of their era of following the sport, as the most complete expression of what a racing driver can be.',
    ],
  },
  {
    driverId: 'prost',
    career: [
      'Alain Prost was called The Professor because he approached Formula 1 with the methodical intelligence of an academic. Where others drove by instinct and aggression, Prost calculated — the minimum fuel load required, the tyre management strategy, the precise braking points that would preserve rubber to the end of a race. He was rarely the fastest driver on any given lap. He was, more often than any of his rivals, the fastest driver across 60 laps.',
      'His first world championship in 1985 was the culmination of four years of sustained excellence at Renault and then McLaren. The title came at Monza, at a race he won while managing exactly the pace his car\'s fuel load permitted — a perfect execution of the Prost formula. His second championship in 1986 came at the final race in Adelaide, secured when his Williams-Honda\'s tyre exploded at over 300 km/h and he coasted to safety, allowing Nigel Mansell — who had seemed to have the title won — to retire with his own tyre failure.',
      'The McLaren years alongside Senna from 1988 produced the most intense intra-team rivalry the sport had seen. Prost\'s statistical record was impeccable: 44 wins across his career, four world championships, seven more than anyone had managed before his retirement in 1993. But the public narrative in those McLaren years was dominated by the conflict with Senna, a conflict that cast Prost as the calculating villain against Senna\'s romantic genius — an assessment that was unfair and has been revised more generously by history.',
      'After retirement, Prost briefly owned and ran the Prost Grand Prix team in Formula 1, a venture that ultimately did not succeed but demonstrated the breadth of his understanding of the sport beyond driving. His legacy in the cockpit is unambiguous: one of the four or five greatest Formula 1 drivers in history, a master of race management whose influence on how drivers approach tyre and fuel conservation continues to be felt.',
    ],
  },
  {
    driverId: 'lauda',
    career: [
      'Niki Lauda is the driver who survived something unsurvivable and came back to nearly win a world championship six weeks later. The 1976 German Grand Prix at the Nürburgring Nordschleife — a circuit Lauda himself had campaigned to have removed from the calendar — produced an accident so severe that he received the last rites of the Catholic Church. Third-degree burns across his face and scalp, smoke inhalation damage to his lungs. He was in a coma.',
      'Forty-two days later, Lauda was racing in Italy at Monza. It remains the most remarkable comeback in the history of any sport. The damaged tissue on his face and eyelids was still raw. He was wearing a specially modified helmet to reduce pressure on his injuries. He finished fourth. The image of Lauda at Monza in September 1976 — blood on his helmet, face bandaged beneath it — is the most striking visual in Formula 1 history.',
      'He came within a hair\'s breadth of the 1976 title, ultimately conceding it to James Hunt in the final race in Japan when he withdrew in the rain because the conditions were too dangerous. The decision — rational, human, the choice of a man who had already nearly died once that season — was initially described as a failure of nerve. Time has re-evaluated it as the correct decision. He won the championship again in 1977 and then, remarkably, won a third title with McLaren in 1984 after a three-year retirement.',
      'Lauda\'s career away from the cockpit was as significant as his driving. As a consultant, team principal, and later non-executive chairman of Mercedes during their dominant hybrid era, he helped construct one of the most successful technical partnerships in the sport\'s history. His relationship with Lewis Hamilton — first persuading him to join Mercedes, then as his confidant through the championship years — was central to everything that followed. He died in 2019, and Formula 1 lost one of its most authentic voices.',
    ],
  },
  {
    driverId: 'alonso',
    career: [
      'Fernando Alonso arrived in Formula 1 in 2001 as a 19-year-old Spaniard with a driving style of startling maturity. His path to the front of the grid was not immediate — he spent 2002 in the junior Minardi team learning the circuits — but his 2003 season at Renault announced him clearly, and his 2005 campaign was one of the most dominant title-winning seasons the sport had produced. At 24, he became the youngest world champion in Formula 1 history, a record he held until Sebastian Vettel broke it six years later.',
      'His single season at McLaren in 2007 was the most publicly uncomfortable of his career. He had chosen McLaren in part because Renault could not match them technically, and instead found himself in an intra-team battle with his new teammate — the 22-year-old rookie Lewis Hamilton — that consumed the entire season. The championship was decided between Hamilton, Alonso, and Kimi Räikkönen at the last race, with Alonso taking a single point fewer than Räikkönen. He returned to Renault the following year.',
      'What followed is the career arc that earns Alonso his place in the greatest-of-all-time conversation: twenty years of Formula 1 in which he remained competitive, season after season, in cars that were not competitive. His 2012 season — in which he nearly won the championship with a Ferrari that was arguably the fourth-fastest car on the grid — is the single most impressive season-long performance in the sport\'s history. He extracted more from his car on more occasions than any driver in any comparable situation.',
      'His return to Formula 1 in 2021, with Renault rebranded as Alpine, and subsequent move to Aston Martin in 2023 produced performances that removed any remaining doubt about whether age had diminished him. At 40, he was still driving at a level that put him in the points regularly and occasionally on the podium. His F1 career is the longest sustained elite performance in the sport\'s history, and it continues — a testament to a competitive drive that appears constitutionally impossible to extinguish.',
    ],
  },
  {
    driverId: 'vettel',
    career: [
      'Sebastian Vettel became Formula 1 world champion for the first time in 2010 at the age of 23, in the most chaotic title decider in decades. Four drivers arrived at the Abu Dhabi season finale with a mathematical possibility of taking the championship — Alonso, Webber, Hamilton, and Vettel. Vettel, starting from pole, managed the race impeccably. Alonso, who needed only to finish fifth, was caught behind a strategy call that dropped him into the midfield and left him watching Vettel take the title. The scale of the victory was immediate: the youngest world champion in Formula 1 history.',
      'Three more championships followed in 2011, 2012, and 2013, all with Red Bull Racing and all underpinned by technical genius from Adrian Newey\'s aerodynamic department and Vettel\'s own capacity to extract performance through engineering feedback. His 2011 season was the most complete he produced — 11 wins from 19 races, pole position at 15 circuits, a technical and driving performance so comprehensive that rivals acknowledged during the season that the competition was essentially between everyone else for second place.',
      'His years at Ferrari from 2015 to 2020 produced individual performances of brilliance without adding to his championship tally. In 2017 and 2018, Vettel challenged Hamilton for the title with a Ferrari that was at times the quicker car, but errors under pressure — Baku 2018 and Germany 2018 in particular — cost him points that may have changed the outcome of those championships. The pressure of leading a Ferrari team with decades of historical weight proved a different environment from the technical culture of Red Bull.',
      'Vettel retired from Formula 1 at the end of 2022, having spent his final two seasons at Aston Martin where he drove competitively but without the machinery to challenge for victories. His post-racing life revealed the environmental and political convictions that he had developed quietly during his career — he became one of the sport\'s most vocal advocates on climate change, plastic pollution, and social justice. The image of Vettel that has emerged after retirement is of a more complex figure than the driven perfectionist the paddock saw behind the wheel.',
    ],
  },
  {
    driverId: 'leclerc',
    career: [
      'Charles Leclerc came through the Ferrari Driver Academy having already demonstrated, in Formula 2, the combination of raw pace and emotional intensity that would define his Formula 1 career. His 2018 debut season with Sauber — a backmarker team — was a consistent exhibition of extracting far more from the car than its machinery entitled him to, regularly matching and occasionally beating well-funded midfield teams in a car that had no business keeping up with them. Ferrari signed him for 2019.',
      'His first year at Ferrari produced his maiden race wins in both Belgium and Italy within the space of a fortnight — two circuits with enormous significance to the team and its fan base. The Monza win was particularly theatrical: Leclerc qualifying on pole, managing a race against Hamilton\'s Mercedes, crossing the line in tears while the tifosi erupted. At 21, he had become the first Ferrari driver to win at Monza since Michael Schumacher in 2006.',
      'The subsequent seasons brought pole positions — Leclerc has an extraordinary natural qualifying ability, consistently extracting every tenth the car is capable of and occasionally finding more — but the championships that should have followed from his pace were obstructed by a combination of car reliability failures at critical moments, strategy errors by the Ferrari pit wall, and the appearance of Red Bull\'s dominance from 2022 onward. The 2022 season, in which Leclerc led the championship after the first two races, was the closest he has come to a title that many observers believe his talent deserves.',
      'His partnership with Lewis Hamilton at Ferrari from 2026 — two of the greatest drivers of their respective generations in the same car — has added a new dynamic to his career. Leclerc brings a qualifying ability and high-speed corner talent that makes him one of the fastest pure drivers in the field; Hamilton brings the championship experience and race management capability of seven titles. The combination is the most fascinating intra-team competition Formula 1 has produced since Senna and Prost at McLaren.',
    ],
  },
  {
    driverId: 'norris',
    career: [
      'Lando Norris joined McLaren in 2019 as a bright-eyed 19-year-old more comfortable on social media than the podium, and spent the early years of his career building a reputation as one of Formula 1\'s most naturally gifted drivers in a car that was chronically uncompetitive. The McLaren of those years was, at best, a midfield threat on circuits that suited it — and yet Norris\'s performances consistently outpaced expectations, demonstrating an instinctive feel for the car that his engineers noted was exceptional even by Formula 1 standards.',
      'His first race win came at Miami in 2024, in a race he dominated from the front after overtaking Max Verstappen\'s Red Bull in a move that confirmed McLaren\'s resurgence had become a genuine threat to the top teams. The relief and emotion at the finish — 110 Formula 1 starts before standing on the top step — was visible from the cockpit camera. Norris had come close before, most notably at Sochi 2021 where he led comfortably until a late rain shower caught him without wet tyres and he dropped from first to seventh on the final lap.',
      'What Norris brings to Formula 1 that is relatively unusual is an exceptional ability to set up a car for his own style. His engineering feedback is detailed and precise enough that McLaren\'s chassis development has been shaped substantially by his input — a quality associated more typically with drivers later in their careers. Combined with his speed over a single lap, his tyre management, and his racecraft, it makes him one of the most complete drivers of his generation.',
      'His openness about the challenges of professional sport — the pressure, the expectation, the difficulty of performing at elite level — has made him one of Formula 1\'s most relatable personalities in an era when the drivers are reaching audiences far beyond the traditional motorsport fan base. He is simultaneously one of the best and one of the most human drivers in the paddock, and that combination has made him one of the sport\'s most compelling figures.',
    ],
  },
  {
    driverId: 'russell',
    career: [
      'George Russell spent three seasons at Williams between 2019 and 2021 in a car that regularly qualified last and rarely finished in the points, but emerged from those years with a reputation enhanced rather than diminished by the experience. His ability to qualify the Williams consistently above where its pace suggested it should be — and to manage it delicately through races to extract whatever results were available — marked him as a driver with exceptional car control and composure under pressure.',
      'His one-race substitute appearance at Bahrain 2020, replacing Lewis Hamilton at Mercedes while Hamilton recovered from Covid-19, came within a pitstop error and a puncture of producing a race win in only his second race in a truly competitive car. The pace he showed that afternoon — immediately at Hamilton\'s level and above Valtteri Bottas\'s — effectively sealed his promotion to Mercedes for 2022 before the team had formally decided it.',
      'His maiden pole position and victory came within the same weekend at the 2022 Brazilian Grand Prix, a performance of such authority — pole by over six tenths, dominant in the wet qualifying session, controlled in the race — that it settled any remaining questions about whether he belonged at the front of the grid. He finished third in the championship that year in his debut season as a Mercedes driver.',
      'Russell\'s character in the paddock is defined by an unusual combination of political intelligence and genuine warmth. He served as the drivers\' representative to the FIA for several years, a role that required diplomatic skill and an ability to represent divergent interests — qualities that made him one of the most respected voices in the paddock beyond his driving ability. His ambition to win a world championship with Mercedes remains undimmed, and the performances he has produced suggest it is when, not whether, it will happen.',
    ],
  },
  {
    driverId: 'sainz',
    career: [
      'Carlos Sainz Junior grew up as the son of a World Rally Championship legend, which brought both an advantage — a natural understanding of high-performance cars at the limit — and a particular kind of pressure. He entered Formula 1 in 2015 with Toro Rosso, Red Bull\'s junior team, and spent four seasons passing through Renault and McLaren before landing at Ferrari in 2021. The journey was a masterclass in consistent excellence and patient career management.',
      'His partnership with Charles Leclerc at Ferrari was one of the most competitive intra-team battles Formula 1 had produced in years. Sainz brought a consistency and calm analytical approach that complemented Leclerc\'s raw pace — he was often the driver extracting points from weekends where Leclerc\'s car failed or where pure lap speed was less important than race management. His first race win came at the 2022 British Grand Prix, a victory managed with intelligence and composure over Hamilton and Pérez.',
      'What distinguishes Sainz is an exceptional ability to deliver in high-pressure moments with unusual calm. Unlike drivers who build momentum and then are disrupted by a bad race, Sainz maintains a baseline of performance that is remarkably consistent. His qualifying average — the ratio of his pace to his fastest teammate\'s pace over a season — is among the best of his generation, a quality that engineers and team principals value perhaps more than fans fully appreciate.',
      'His move away from Ferrari after 2024 to join Williams brought a new chapter to his career. The challenge of lifting Williams back to competitiveness is one he has approached with the same methodical confidence that has characterised his career from the beginning. Formula 1 history is full of examples of drivers who improved cars through the quality of their feedback and their ability to focus team effort productively — Sainz is building that reputation with every race.',
    ],
  },
  {
    driverId: 'perez',
    career: [
      'Sergio Pérez spent a decade in Formula 1 in cars that were good but never quite good enough, accumulating the experience and the skills — particularly his legendary tyre management — that eventually delivered him a seat in the best car on the grid. His years at Sauber, McLaren, and Force India/Racing Point produced occasional brilliance — a stunning win in the rain at Sakhir 2020 in a substitute appearance for Hamilton that showcased his abilities at their fullest — but mostly the quiet work of a driver extracting more than his car offered.',
      'The Red Bull years from 2021 onward brought him to the front of Formula 1 and revealed both the ceiling of his ability and the specific qualities that made him invaluable to a team chasing world constructors\' championships. His wins in Baku, Monaco, Singapore, and other circuits that reward tyre longevity and race management over single-lap pace were exactly the performances Red Bull needed from their second driver to accumulate the points that championship challenges demand.',
      'His partnership with Verstappen produced the most dominant car-pairing in recent Formula 1 history. While Verstappen was winning 15 races in 2022 and 19 in 2023, Pérez was contributing second, third, and fourth-place finishes across the season — points that compounded into a constructors\' championship margin of historic proportions. His role as a supporting driver was performed at a level that exceeded any comparable second driver in recent memory.',
      'Pérez\'s significance to Mexican motorsport extends well beyond his results. He has built a following in Mexico that rivals the crowd at the Mexican Grand Prix itself — one of the best-attended races on the calendar — and has inspired a generation of young Mexican drivers and motorsport fans. His career is a reminder that Formula 1 rewards not just raw pace but the complete package of skills, and that tyre management and race intelligence are as valuable as any qualifying lap.',
    ],
  },
  {
    driverId: 'ricciardo',
    career: [
      'Daniel Ricciardo has the most unreliable relationship with good fortune in the history of Formula 1, and the smile with which he has faced that unreliability is one of the sport\'s most characteristic images. He arrived at Red Bull in 2014 as the replacement for Mark Webber, immediately outscored his four-time world champion teammate Sebastian Vettel, and won three races — including Monaco — in his debut season with the team. It announced a driver of world championship potential.',
      'His Red Bull years produced seven race victories and some of the sport\'s most memorable overtaking moves — his dive on Rosberg at Monaco in 2016, his pass on Vettel under braking at Monza in 2017, his overtake on Verstappen in China in 2018 under braking so late that the physics appeared negotiable. His braking ability was categorically exceptional: later than almost any driver in the field, with the precision to make it work when it should have been impossible.',
      'He left Red Bull for Renault in 2019 seeking to win the championship with a different team — a gamble that did not pay off as Renault did not improve as quickly as anticipated. A subsequent move to McLaren in 2021 produced his most emotional and arguably most surprising victory: the 2021 Italian Grand Prix at Monza, where he led McLaren to a one-two finish with Norris in the first McLaren victory in nine years. The podium celebration was one of the most joyful in modern Formula 1 history.',
      'The seasons after Monza brought difficulties that were difficult to explain statistically. His pace seemed to have departed, and a return to Red Bull as reserve driver in 2023 did not produce the results that would have earned him a permanent seat. His relationship with Formula 1 remained warm and his affection for the sport genuine — few drivers have contributed more to its personality and entertainment value than Ricciardo, whose natural exuberance and wit made him one of the sport\'s most beloved figures.',
    ],
  },
  {
    driverId: 'gasly',
    career: [
      'Pierre Gasly\'s Formula 1 career is a story of two distinct acts separated by one of the sport\'s most dramatic public demotions. He entered Formula 1 with Toro Rosso in 2017, graduated to Red Bull Racing in 2019, and within the first half of that season was comprehensively outpaced by his new teammate Max Verstappen while struggling with the pressure of driving the second-fastest car in the field. Red Bull made the decision to demote him back to Toro Rosso mid-season — a public and humbling verdict.',
      'What followed was one of the most compelling character responses in modern Formula 1. Rather than being diminished by the experience, Gasly rebuilt his confidence at Toro Rosso (later Alpha Tauri) and produced the performance of his life at the 2020 Italian Grand Prix — a rain-affected, chaotic race at Monza that produced a chain of safety car deployments and retirements that left Gasly at the front. He managed the final laps with composure that his Red Bull year had suggested he lacked, and crossed the line to win his maiden Grand Prix in floods of tears.',
      'His subsequent move to Alpine in 2023 gave him a car in which he was regularly competitive in the midfield — not at the front of the grid, but operating at a level that vindicated his decision to remain in Formula 1 rather than accepting a career in a junior category. His qualifying pace, always his greatest strength, continued to produce performances that kept him visible in a tightly contested midfield.',
      'Gasly\'s story matters to Formula 1 beyond his results. He is an example of a driver who absorbed failure, learned from it, and returned to produce performances that justify his place at the highest level of motorsport. The 2020 Monza victory is one of the sport\'s most unexpected and emotionally resonant results — a driver who had been publicly written off winning a Formula 1 race a year after the verdict against him was delivered.',
    ],
  },
  {
    driverId: 'ocon',
    career: [
      'Esteban Ocon\'s path to Formula 1 victory passed through one of the most complicated personal histories in the paddock. He grew up in Normandy with parents who sold their house to finance his karting career, driving while staying in a motorhome in which the family lived at circuits. The investment was validated when he broke into Formula 1 via the Mercedes junior programme and eventually reached the grid permanently with Force India in 2017.',
      'His partnership at Force India with Pérez produced a level of intra-team competition that the team, genuinely competitive in midfield terms, struggled to manage diplomatically. Both drivers were faster than the car\'s position in the championship suggested and both were making claims on a future seat at a top team. The rivalry occasionally spilled onto the track in ways that cost both of them.',
      'His victory at the 2021 Hungarian Grand Prix was one of the most unlikely — and most deserved — race wins of the turbo-hybrid era. Strategy chaos during a first-lap incident reshuffled the grid dramatically, and Ocon found himself leading in an Alpine. He managed the race impeccably for the remainder of the distance, resisting increasing pressure from Sebastian Vettel (later disqualified) and Hamilton behind him, to score his and Alpine\'s maiden Formula 1 victory. The emotion at the finish was raw and genuine.',
      'Ocon\'s career has been defined by resilience in a paddock where backing, contracts, and politics play as large a role as performance. He has navigated those challenges with a stubbornness and professionalism that has kept him on the grid when drivers with stronger backing would have preferred his seat. His ability in the wet, his tyre management, and his capacity to deliver on strategic opportunities make him a driver who punches above the weight of his car on a consistent basis.',
    ],
  },
  {
    driverId: 'piastri',
    career: [
      'Oscar Piastri won the Formula 2 championship in 2021 and the Formula 3 championship the year before that, making him the most decorated junior driver in the recent history of the feeder categories. And yet his path to a Formula 1 race seat was blocked — Alpine had signed him as a reserve driver, Renault before them had funded his career, and when Fernando Alonso vacated the Alpine race seat for 2023, a contract dispute that went to the Contract Recognition Board determined that Piastri had actually been contracted to McLaren rather than Alpine. He joined McLaren for 2023 as a genuine Formula 1 rookie.',
      'His debut season confirmed what the junior categories had suggested: exceptional technical intelligence, a near-flawless approach to race management, and a qualifying ability that was immediately within the same range as his more experienced teammate Lando Norris. He took his first race victory at the 2024 Hungarian Grand Prix in a race that McLaren had dominated from start to finish — a controlled, measured display that felt entirely natural for a driver in only his second season.',
      'What distinguishes Piastri is a coolness under pressure that is unusual even by Formula 1 standards. He does not appear rattled by close racing, does not make emotional decisions in traffic, and manages his tyres across a race distance with a patience that usually takes drivers years to develop. His car setup feedback is detailed and useful — McLaren\'s engineers have spoken publicly about how quickly he adapted to providing development-quality information.',
      'At an age when most Formula 1 drivers are still working out how to extract everything from the car, Piastri is already shaping the car around his needs. The combination of his natural pace, his emotional control, and his technical intelligence places him among the highest-ceiling drivers in a generation of exceptional Formula 1 talent. He is, in the assessment of most people who have watched his career closely, a future world champion — and probably more than once.',
    ],
  },
  {
    driverId: 'antonelli',
    career: [
      'Andrea Kimi Antonelli was identified as a generational talent before he was old enough to hold a road licence. Born in Bologna in 2006, he was brought into the Mercedes junior programme as a child and moved through the karting ranks with the kind of results that make a manufacturer reorganise its plans around a single driver. Toto Wolff spoke about him for years in terms usually reserved for drivers already in Formula 1 — a level of public confidence from a team principal that placed an extraordinary weight of expectation on a teenager who had not yet raced a single-seater.',
      'He justified all of it. In 2022 he won both the Italian and German Formula 4 championships in the same season, and in 2023 he took the Formula Regional European and Middle East titles back to back — dominating each category in the way that only the rarest junior drivers do. Mercedes then made the unusually aggressive decision to skip Formula 3 entirely and place him straight into Formula 2 for 2024, a step up so steep that it is almost never attempted, and he won on his feature-race debut at Melbourne to show the gamble was sound.',
      'The decision that defined his early career came for 2025, when Mercedes promoted him directly into their Formula 1 race seat to replace Lewis Hamilton — handing an 18-year-old the cockpit that had carried seven world championships. It was one of the boldest driver calls the modern paddock has seen. His rookie season answered the doubt with composure rather than recklessness: a maiden podium and repeated flashes of genuine front-running pace, delivered with a maturity that made his age easy to forget.',
      'In 2026 the prodigy turned promise into a defining result with a pole-to-flag victory at Monaco — the most demanding circuit on the calendar to lead from the front, where a single lapse over seventy-eight laps ends the race against the barriers. To control it from pole as a teenager, against the most experienced grid in the sport, was the performance that moved Antonelli from "future of Mercedes" to a driver the rest of the grid now has to account for. The ceiling, on the evidence so far, is as high as anyone\'s in the field.',
    ],
  },
  {
    driverId: 'raikkonen',
    career: [
      'Kimi Räikkönen arrived in Formula 1 in 2001 with one of the thinnest résumés in the sport\'s history — just 23 car races before his Sauber debut — and a superlicence granted only after officials were persuaded he was an exception to every rule about experience. He answered the doubt on his first weekend, scoring points at the Australian Grand Prix, and within a year McLaren had signed him to replace Mika Häkkinen. The raw, almost eerie natural speed was obvious immediately; so was the indifference to everything around it that would make him the most distinctive personality of his generation.',
      'The McLaren years from 2002 to 2006 should have brought a championship and, but for serial mechanical failures, probably would have. He lost the 2003 and 2005 titles as much to unreliability as to anyone\'s driving, and the 2005 season in particular — including a last-lap pass on Giancarlo Fisichella at Suzuka after starting seventeenth — established him as perhaps the fastest pure racer on the grid. When the wins came they were often spectacular, carved out from grid positions that should have made them impossible.',
      'His world championship came in 2007, his first year at Ferrari, in the closest finish the sport had seen. Räikkönen trailed the two feuding McLarens of Hamilton and Alonso with two races to go and won both, taking the title at the final round in Brazil by a single point. It was a championship won on raw pace and ruthless execution at exactly the moment it was needed — the last Ferrari drivers\' title for fifteen years, and the validation of a talent that had always deserved one.',
      'After a sabbatical in rallying, Räikkönen returned in 2012 and reminded everyone he had lost nothing, winning in Abu Dhabi with the famous radio message telling his engineers to leave him alone. A second Ferrari spell and a long final chapter at Sauber and Alfa Romeo followed, where he became the most experienced driver in the sport\'s history. The deadpan one-liners turned him into a cult figure, but underneath the "Iceman" persona was one of the most naturally gifted drivers ever to sit in a Formula 1 car.',
    ],
  },
  {
    driverId: 'rosberg',
    career: [
      'Nico Rosberg carried a Formula 1 surname before he ever drove the car — his father Keke was the 1982 world champion — but he built his own career on method rather than inheritance. Fluent in five languages and analytical to the core, he entered the sport with Williams in 2006, marking his debut at Bahrain with the fastest lap and an immediate reputation as a thinking driver. Through four seasons at a declining Williams he showed flashes of the front-running pace the car rarely allowed him to convert.',
      'His move to Mercedes in 2010 placed him alongside the returning Michael Schumacher, and Rosberg consistently out-scored the seven-time champion over their three years together — quiet evidence of his quality that the wider paddock was slow to acknowledge. His first win came in China in 2012, and as Mercedes built toward the hybrid era he positioned himself perfectly: established, fast, and embedded at the team that was about to dominate Formula 1 completely.',
      'From 2014 the Mercedes years became a private war with Lewis Hamilton, his childhood karting friend turned fiercest rival. For three seasons they fought for championships in the same dominant car, a contest that grew increasingly bitter — Spa 2014, the collision in Spain 2016, the cold silences. Rosberg lost the 2014 and 2015 titles but refused to break, reorganising his entire approach around the single goal of beating the most complete driver of the era in equal machinery.',
      'In 2016 he did it. A season of relentless precision, capitalising on every Hamilton misfortune and giving nothing away under extraordinary pressure, delivered the world championship by five points — sealed with a nerveless drive at Abu Dhabi. Then, five days later, Rosberg retired. At 31, as reigning world champion, he simply walked away, having achieved the one thing he had built his entire life around. It remains one of the most singular decisions in the sport\'s history.',
    ],
  },
]

export function getDriverCareer(driverId: string): string[] {
  return DRIVER_CAREERS.find((d) => d.driverId === driverId)?.career ?? []
}
