export interface DriverCareer {
  driverId: string
  career: string[]
}

export const DRIVER_CAREERS: DriverCareer[] = [
  {
    driverId: 'hamilton',
    career: [
      'Lewis Hamilton arrived in Formula 1 in 2007 as the most hyped rookie in the sport\'s history, and he immediately justified it. In his debut season at McLaren he pushed world champion Fernando Alonso to a third-place finish in the championship — as a first-year driver — and came within a single point of winning the title. It was an entrance unlike any other, and it announced not just a driver of exceptional talent but one who appeared immune to pressure at the highest level.',
      'His first world championship came in 2008 in the most dramatic fashion possible: on the final corner of the final lap of the final race in Brazil. Hamilton overtook Timo Glock in the wet at Interlagos to take the fifth place he needed to claim the title by a single point from Felipe Massa. It was a conclusion so cinematic that it defined the early image of Hamilton as a driver who seemed destined to be at the centre of Formula 1\'s greatest moments.',
      'The years with Mercedes from 2013 onward transformed Hamilton from a very good Formula 1 champion into the statistical greatest of all time. Six more titles between 2014 and 2020, including a 2019 and 2020 run so dominant that his records for most wins and most pole positions became essentially unreachable for any current driver. His 2020 season — 11 wins from 17 races in a shortened pandemic campaign — was the most authoritative individual performance in the hybrid era.',
    ],
  },
  {
    driverId: 'verstappen',
    career: [
      'Max Verstappen became the youngest Formula 1 race winner in history when he won the 2016 Spanish Grand Prix on his debut for Red Bull Racing at the age of 18 years and 228 days. The win was not a fluke — he passed Kimi Räikkönen\'s Ferrari in the closing stages with the assurance of a driver twice his age. Formula 1 had seen prodigies before, but the manner of Verstappen\'s arrival suggested something qualitatively different: not just a fast young driver, but one who appeared to have skipped the learning phase entirely.',
      'His path to the 2021 World Championship was the most contested in the hybrid era. Through 22 races, he and Lewis Hamilton traded victories and collisions — Silverstone, Monza, Saudi Arabia — in a season that raised every question Formula 1 asks about the boundary between racing and foul play. The title was decided at Abu Dhabi on the final lap under circumstances so controversial that they prompted a fundamental restructuring of how the sport manages its race direction.',
      'What followed was even more emphatic. In 2022, Verstappen won 15 of 22 races, clinching the championship with four races remaining. In 2023, he won 19 races — a record that seemed impossible until he did it. By 2024, he had four consecutive world championships and had already established himself in the conversation about the greatest Formula 1 driver of all time, a conversation that would have seemed absurd to even broach about any driver at 27 years old.',
      'Verstappen\'s driving style combines raw pace with an almost preternatural ability to manage tyres, manage traffic, and extract performance from a car across a full race distance. His overtaking ability — particularly late-braking moves into tight corners — is as aggressive as any driver in the sport\'s history, and his wheel-to-wheel racecraft recalls Michael Schumacher in its absolute refusal to yield without a fight.',
    ],
  },
  {
    driverId: 'vettel',
    career: [
      'Sebastian Vettel became Formula 1 world champion for the first time in 2010 at the age of 23, in the most chaotic title decider in decades. Four drivers arrived at the Abu Dhabi season finale with a mathematical possibility of taking the championship — Alonso, Webber, Hamilton, and Vettel. Vettel, starting from pole, managed the race impeccably. Alonso, who needed only to finish fifth, was caught behind a strategy call that dropped him into the midfield and left him watching Vettel take the title. The scale of the victory was immediate: the youngest world champion in Formula 1 history.',
      'Three more championships followed in 2011, 2012, and 2013, all with Red Bull Racing and all underpinned by technical genius from Adrian Newey\'s aerodynamic department and Vettel\'s own capacity to extract performance through engineering feedback. His 2011 season was the most complete he produced — 11 wins from 19 races, pole position at 15 circuits, a technical and driving performance so comprehensive that rivals acknowledged during the season that the competition was essentially between everyone else for second place.',
      'His years at Ferrari from 2015 to 2020 produced individual performances of brilliance without adding to his championship tally. In 2017 and 2018, Vettel challenged Hamilton for the title with a Ferrari that was at times the quicker car, but errors under pressure — Baku 2018 and Germany 2018 in particular — cost him points that may have changed the outcome of those championships. The pressure of leading a Ferrari team with decades of historical weight proved a different environment from the technical culture of Red Bull.',
      'Vettel retired from Formula 1 at the end of 2022, having spent his final two seasons at Aston Martin where he drove competitively but without the machinery to challenge for victories. His post-racing life revealed the environmental and political convictions that he had developed quietly during his career — he became one of the sport\'s most vocal advocates on climate change, plastic pollution, and social justice. The image of Vettel that has emerged after retirement is of a more complex figure than the driven perfectionist the paddock saw behind the wheel.',
    ],
  },
  {
    driverId: 'leclerc',
    career: [
      'Charles Leclerc came through the Ferrari Driver Academy having already demonstrated, in Formula 2, the combination of raw pace and emotional intensity that would define his Formula 1 career. His 2018 debut season with Sauber — a backmarker team — was a consistent exhibition of extracting far more from the car than its machinery entitled him to, regularly matching and occasionally beating well-funded midfield teams in a car that had no business keeping up with them. Ferrari signed him for 2019.',
      'His first year at Ferrari produced his maiden race wins in both Belgium and Italy within the space of a fortnight — two circuits with enormous significance to the team and its fan base. The Monza win was particularly theatrical: Leclerc qualifying on pole, managing a race against Hamilton\'s Mercedes, crossing the line in tears while the tifosi erupted. At 21, he had become the first Ferrari driver to win at Monza since Michael Schumacher in 2006.',
      'The subsequent seasons brought pole positions — Leclerc has an extraordinary natural qualifying ability, consistently extracting every tenth the car is capable of and occasionally finding more — but the championships that should have followed from his pace were obstructed by a combination of car reliability failures at critical moments, strategy errors by the Ferrari pit wall, and the appearance of Red Bull\'s dominance from 2022 onward. The 2022 season, in which Leclerc led the championship after the first two races, was the closest he has come to a title that many observers believe his talent deserves.',
    ],
  },
  {
    driverId: 'norris',
    career: [
      'Lando Norris joined McLaren in 2019 as a bright-eyed 19-year-old more comfortable on social media than the podium, and spent the early years of his career building a reputation as one of Formula 1\'s most naturally gifted drivers in a car that was chronically uncompetitive. The McLaren of those years was, at best, a midfield threat on circuits that suited it — and yet Norris\'s performances consistently outpaced expectations, demonstrating an instinctive feel for the car that his engineers noted was exceptional even by Formula 1 standards.',
      'His first race win came at Miami in 2024, in a race he dominated from the front after overtaking Max Verstappen\'s Red Bull in a move that confirmed McLaren\'s resurgence had become a genuine threat to the top teams. The relief and emotion at the finish — 110 Formula 1 starts before standing on the top step — was visible from the cockpit camera. Norris had come close before, most notably at Sochi 2021 where he led comfortably until a late rain shower caught him without wet tyres and he dropped from first to seventh on the final lap.',
      'What Norris brings to Formula 1 that is relatively unusual is an exceptional ability to set up a car for his own style. His engineering feedback is detailed and precise enough that McLaren\'s chassis development has been shaped substantially by his input — a quality associated more typically with drivers later in their careers. Combined with his speed over a single lap, his tyre management, and his racecraft, it makes him one of the most complete drivers of his generation.',
      'His openness about the challenges of professional sport — the pressure, the expectation, the difficulty of performing at elite level — has made him one of Formula 1\'s most relatable personalities in an era when the drivers are reaching audiences far beyond the traditional motorsport fan base. He is simultaneously one of the best and one of the most human drivers in the paddock, and that combination has made him one of the sport\'s most compelling figures.',
    ],
  },
  {
    driverId: 'russell',
    career: [
      'George Russell spent three seasons at Williams between 2019 and 2021 in a car that regularly qualified last and rarely finished in the points, but emerged from those years with a reputation enhanced rather than diminished by the experience. His ability to qualify the Williams consistently above where its pace suggested it should be — and to manage it delicately through races to extract whatever results were available — marked him as a driver with exceptional car control and composure under pressure.',
      'His one-race substitute appearance at Bahrain 2020, replacing Lewis Hamilton at Mercedes while Hamilton recovered from Covid-19, came within a pitstop error and a puncture of producing a race win in only his second race in a truly competitive car. The pace he showed that afternoon — immediately at Hamilton\'s level and above Valtteri Bottas\'s — effectively sealed his promotion to Mercedes for 2022 before the team had formally decided it.',
      'His maiden pole position and victory came within the same weekend at the 2022 Brazilian Grand Prix, a performance of such authority — pole by over six tenths, dominant in the wet qualifying session, controlled in the race — that it settled any remaining questions about whether he belonged at the front of the grid. He finished third in the championship that year in his debut season as a Mercedes driver.',
      'Russell\'s character in the paddock is defined by an unusual combination of political intelligence and genuine warmth. He served as the drivers\' representative to the FIA for several years, a role that required diplomatic skill and an ability to represent divergent interests — qualities that made him one of the most respected voices in the paddock beyond his driving ability. His ambition to win a world championship with Mercedes remains undimmed, and the performances he has produced suggest it is when, not whether, it will happen.',
    ],
  },
  {
    driverId: 'sainz',
    career: [
      'Carlos Sainz Junior grew up as the son of a World Rally Championship legend, which brought both an advantage — a natural understanding of high-performance cars at the limit — and a particular kind of pressure. He entered Formula 1 in 2015 with Toro Rosso, Red Bull\'s junior team, and spent four seasons passing through Renault and McLaren before landing at Ferrari in 2021. The journey was a masterclass in consistent excellence and patient career management.',
      'His partnership with Charles Leclerc at Ferrari was one of the most competitive intra-team battles Formula 1 had produced in years. Sainz brought a consistency and calm analytical approach that complemented Leclerc\'s raw pace — he was often the driver extracting points from weekends where Leclerc\'s car failed or where pure lap speed was less important than race management. His first race win came at the 2022 British Grand Prix, a victory managed with intelligence and composure over Hamilton and Pérez.',
      'What distinguishes Sainz is an exceptional ability to deliver in high-pressure moments with unusual calm. Unlike drivers who build momentum and then are disrupted by a bad race, Sainz maintains a baseline of performance that is remarkably consistent. His qualifying average — the ratio of his pace to his fastest teammate\'s pace over a season — is among the best of his generation, a quality that engineers and team principals value perhaps more than fans fully appreciate.',
      'His move away from Ferrari after 2024 to join Williams brought a new chapter to his career. The challenge of lifting Williams back to competitiveness is one he has approached with the same methodical confidence that has characterised his career from the beginning. Formula 1 history is full of examples of drivers who improved cars through the quality of their feedback and their ability to focus team effort productively — Sainz is building that reputation with every race.',
    ],
  },
  {
    driverId: 'perez',
    career: [
      'Sergio Pérez spent a decade in Formula 1 in cars that were good but never quite good enough, accumulating the experience and the skills — particularly his legendary tyre management — that eventually delivered him a seat in the best car on the grid. His years at Sauber, McLaren, and Force India/Racing Point produced occasional brilliance — a stunning win in the rain at Sakhir 2020 in a substitute appearance for Hamilton that showcased his abilities at their fullest — but mostly the quiet work of a driver extracting more than his car offered.',
      'The Red Bull years from 2021 onward brought him to the front of Formula 1 and revealed both the ceiling of his ability and the specific qualities that made him invaluable to a team chasing world constructors\' championships. His wins in Baku, Monaco, Singapore, and other circuits that reward tyre longevity and race management over single-lap pace were exactly the performances Red Bull needed from their second driver to accumulate the points that championship challenges demand.',
      'His partnership with Verstappen produced the most dominant car-pairing in recent Formula 1 history. While Verstappen was winning 15 races in 2022 and 19 in 2023, Pérez was contributing second, third, and fourth-place finishes across the season — points that compounded into a constructors\' championship margin of historic proportions. His role as a supporting driver was performed at a level that exceeded any comparable second driver in recent memory.',
      'Pérez\'s significance to Mexican motorsport extends well beyond his results. He has built a following in Mexico that rivals the crowd at the Mexican Grand Prix itself — one of the best-attended races on the calendar — and has inspired a generation of young Mexican drivers and motorsport fans. His career is a reminder that Formula 1 rewards not just raw pace but the complete package of skills, and that tyre management and race intelligence are as valuable as any qualifying lap.',
    ],
  },
  {
    driverId: 'ocon',
    career: [
      'Esteban Ocon\'s path to Formula 1 victory passed through one of the most complicated personal histories in the paddock. He grew up in Normandy with parents who sold their house to finance his karting career, driving while staying in a motorhome in which the family lived at circuits. The investment was validated when he broke into Formula 1 via the Mercedes junior programme and eventually reached the grid permanently with Force India in 2017.',
      'His partnership at Force India with Pérez produced a level of intra-team competition that the team, genuinely competitive in midfield terms, struggled to manage diplomatically. Both drivers were faster than the car\'s position in the championship suggested and both were making claims on a future seat at a top team. The rivalry occasionally spilled onto the track in ways that cost both of them.',
      'His victory at the 2021 Hungarian Grand Prix was one of the most unlikely — and most deserved — race wins of the turbo-hybrid era. Strategy chaos during a first-lap incident reshuffled the grid dramatically, and Ocon found himself leading in an Alpine. He managed the race impeccably for the remainder of the distance, resisting increasing pressure from Sebastian Vettel (later disqualified) and Hamilton behind him, to score his and Alpine\'s maiden Formula 1 victory. The emotion at the finish was raw and genuine.',
      'Ocon\'s career has been defined by resilience in a paddock where backing, contracts, and politics play as large a role as performance. He has navigated those challenges with a stubbornness and professionalism that has kept him on the grid when drivers with stronger backing would have preferred his seat. His ability in the wet, his tyre management, and his capacity to deliver on strategic opportunities make him a driver who punches above the weight of his car on a consistent basis.',
    ],
  },
  {
    driverId: 'piastri',
    career: [
      'Oscar Piastri won the Formula 2 championship in 2021 and the Formula 3 championship the year before that, making him the most decorated junior driver in the recent history of the feeder categories. And yet his path to a Formula 1 race seat was blocked — Alpine had signed him as a reserve driver, Renault before them had funded his career, and when Fernando Alonso vacated the Alpine race seat for 2023, a contract dispute that went to the Contract Recognition Board determined that Piastri had actually been contracted to McLaren rather than Alpine. He joined McLaren for 2023 as a genuine Formula 1 rookie.',
      'His debut season confirmed what the junior categories had suggested: exceptional technical intelligence, a near-flawless approach to race management, and a qualifying ability that was immediately within the same range as his more experienced teammate Lando Norris. He took his first race victory at the 2024 Hungarian Grand Prix in a race that McLaren had dominated from start to finish — a controlled, measured display that felt entirely natural for a driver in only his second season.',
      'What distinguishes Piastri is a coolness under pressure that is unusual even by Formula 1 standards. He does not appear rattled by close racing, does not make emotional decisions in traffic, and manages his tyres across a race distance with a patience that usually takes drivers years to develop. His car setup feedback is detailed and useful — McLaren\'s engineers have spoken publicly about how quickly he adapted to providing development-quality information.',
      'At an age when most Formula 1 drivers are still working out how to extract everything from the car, Piastri is already shaping the car around his needs. The combination of his natural pace, his emotional control, and his technical intelligence places him among the highest-ceiling drivers in a generation of exceptional Formula 1 talent. He is, in the assessment of most people who have watched his career closely, a future world champion — and probably more than once.',
    ],
  },
  {
    driverId: 'raikkonen',
    career: [
      'Kimi Räikkönen arrived in Formula 1 in 2001 with one of the thinnest résumés in the sport\'s history — just 23 car races before his Sauber debut — and a superlicence granted only after officials were persuaded he was an exception to every rule about experience. He answered the doubt on his first weekend, scoring points at the Australian Grand Prix, and within a year McLaren had signed him to replace Mika Häkkinen. The raw, almost eerie natural speed was obvious immediately; so was the indifference to everything around it that would make him the most distinctive personality of his generation.',
      'The McLaren years from 2002 to 2006 should have brought a championship and, but for serial mechanical failures, probably would have. He lost the 2003 and 2005 titles as much to unreliability as to anyone\'s driving, and the 2005 season in particular — including a last-lap pass on Giancarlo Fisichella at Suzuka after starting seventeenth — established him as perhaps the fastest pure racer on the grid. When the wins came they were often spectacular, carved out from grid positions that should have made them impossible.',
      'His world championship came in 2007, his first year at Ferrari, in the closest finish the sport had seen. Räikkönen trailed the two feuding McLarens of Hamilton and Alonso with two races to go and won both, taking the title at the final round in Brazil by a single point. It was a championship won on raw pace and ruthless execution at exactly the moment it was needed — the last Ferrari drivers\' title for fifteen years, and the validation of a talent that had always deserved one.',
      'After a sabbatical in rallying, Räikkönen returned in 2012 and reminded everyone he had lost nothing, winning in Abu Dhabi with the famous radio message telling his engineers to leave him alone. A second Ferrari spell and a long final chapter at Sauber and Alfa Romeo followed, where he became the most experienced driver in the sport\'s history. The deadpan one-liners turned him into a cult figure, but underneath the "Iceman" persona was one of the most naturally gifted drivers ever to sit in a Formula 1 car.',
    ],
  },
  {
    driverId: 'bearman',
    career: [
      'Oliver Bearman arrived in single-seaters as one of the most highly rated products of the Ferrari Driver Academy, and he made the case immediately. In 2021 he won both the Italian Formula 4 and the ADAC German Formula 4 championships in the same season with Van Amersfoort Racing — a dominant junior campaign that marked him out as the standout British prospect of his generation.',
      'He stepped up through FIA Formula 3 in 2022 and into Formula 2 with Prema in 2023, where as a rookie he won multiple feature races and ran near the front against far more experienced drivers. By the start of 2024 he was the most talked-about young driver on the Ferrari books, waiting for a Formula 1 opportunity that arrived far sooner, and far more dramatically, than anyone expected.',
      'That opportunity came at the 2024 Saudi Arabian Grand Prix. Carlos Sainz was ruled out on the morning of qualifying with appendicitis, and Bearman — eighteen years old, with no prior Formula 1 race weekend — was dropped into a Ferrari at one of the fastest and most unforgiving street circuits on the calendar. He qualified eleventh, then drove a composed, mistake-free race to finish seventh, scoring points on his debut and becoming the youngest driver ever to race for Ferrari. Further substitute outings for Haas later that season only reinforced the verdict.',
      'On the strength of that performance, Haas signed him to a full-time race seat for 2025 alongside Esteban Ocon. The Jeddah drive remains the defining image of his early career: a teenager handed an impossible assignment at no notice, who answered it with the calm of a driver who had been doing it for years.',
    ],
  },
  {
    driverId: 'hulkenberg',
    career: [
      'Nico Hülkenberg arrived in Formula 1 in 2010 with one of the most decorated junior records of his generation — champion of the GP2 Series at the first attempt in 2009 — and almost immediately produced one of the great qualifying performances of the era. At the 2010 Brazilian Grand Prix, in a Williams that had no business being near the front, he took a stunning pole position in changeable conditions, beating the entire field by over a second. It was the first signal of a recurring theme: raw single-lap speed that flattered the machinery he was given.',
      'What followed was a career defined by a strange and cruel statistic. Across spells at Williams, Force India, Sauber and Renault, Hülkenberg established himself as one of the most reliable and respected drivers on the grid — quick, racecraft-savvy, and metronomically consistent in the midfield — yet the podium kept eluding him. He accumulated the unwanted record for the most Grand Prix starts without a top-three finish, a run so long it became the defining narrative around him, overshadowing a 2015 Le Mans 24 Hours victory on his debut and a reputation as the best stand-in driver in the sport.',
      'The breakthrough finally came at the 2025 British Grand Prix. Starting nineteenth in a Sauber, Hülkenberg drove a faultless wet-weather race, picking off cars through the chaos at Silverstone to finish third — his first Formula 1 podium after a record-breaking wait that the entire paddock had come to see as one of the sport\'s great injustices. The release of fifteen years of near-misses made it one of the most popular results in recent memory, and set up his move to the works Audi team for the new era.',
    ],
  },
]

export function getDriverCareer(driverId: string): string[] {
  return DRIVER_CAREERS.find((d) => d.driverId === driverId)?.career ?? []
}
