import type { GalleryItem } from './types'

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'perfect_lap',
    title: 'The Perfect Lap',
    subtitle: 'Senna — Monaco 1984',
    driverId: 'senna',
    raceId: 'senna_monaco_1984',
    circuitId: 'monaco',
    driverColor: '#38b000',
    theme: 'championship_gold',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Icon',
  },
  {
    id: 'rain_master',
    title: 'Rain Master',
    subtitle: 'Schumacher — Spa 1995',
    driverId: 'schumacher',
    raceId: 'schumacher_spa_1995',
    circuitId: 'spa',
    driverColor: '#dc0000',
    theme: 'blueprint',
    vizMode: 'speed_heatmap',
    isPremium: true,
    badge: 'Legendary',
  },
  {
    id: 'last_lap_king',
    title: 'Last Lap King',
    subtitle: 'Verstappen — Abu Dhabi 2021',
    driverId: 'verstappen',
    raceId: 'verstappen_abu_dhabi_2021',
    circuitId: 'abu_dhabi',
    driverColor: '#1e41ff',
    theme: 'neon_racing',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Historic',
  },
  {
    id: 'seven_nation',
    title: 'Seven Nation',
    subtitle: 'Hamilton — Silverstone 2020',
    driverId: 'hamilton',
    raceId: 'hamilton_silverstone_2020',
    circuitId: 'silverstone',
    driverColor: '#00d2be',
    theme: 'carbon_fiber',
    vizMode: 'racing_line',
    isPremium: false,
  },
  {
    id: 'street_poet',
    title: 'Street Poet',
    subtitle: 'Alonso — Monaco 2006',
    driverId: 'alonso',
    raceId: 'alonso_monaco_2006',
    circuitId: 'monaco',
    driverColor: '#ffd700',
    theme: 'monaco_night',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Premium',
  },
  {
    id: 'phoenix',
    title: 'Phoenix',
    subtitle: 'Lauda — Monza 1976',
    driverId: 'lauda',
    raceId: 'lauda_monza_1976',
    circuitId: 'monza',
    driverColor: '#e8002d',
    theme: 'vintage_f1',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Courage',
  },
  {
    id: 'professor_monza',
    title: 'The Professor',
    subtitle: 'Prost — Monza 1985',
    driverId: 'prost',
    raceId: 'prost_monza_1985',
    circuitId: 'monza',
    driverColor: '#ff6b00',
    theme: 'podium_champagne',
    vizMode: 'racing_line',
    isPremium: true,
  },
  {
    id: 'desert_duel',
    title: 'Desert Duel',
    subtitle: 'Hamilton — Bahrain 2014',
    driverId: 'hamilton',
    raceId: 'hamilton_bahrain_2014',
    circuitId: 'bahrain',
    driverColor: '#00d2be',
    theme: 'championship_gold',
    vizMode: 'racing_line',
    isPremium: false,
  },
  {
    id: 'champion_home',
    title: 'Champion at Home',
    subtitle: 'Senna — Brazil 1991',
    driverId: 'senna',
    raceId: 'senna_brazil_1991',
    circuitId: 'interlagos',
    driverColor: '#38b000',
    theme: 'neon_racing',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Legend',
  },
  {
    id: 'schumacher_title',
    title: 'The Equalizer',
    subtitle: 'Schumacher — Suzuka 2000',
    driverId: 'schumacher',
    raceId: 'schumacher_suzuka_2000',
    circuitId: 'suzuka',
    driverColor: '#dc0000',
    theme: 'helmet_cam',
    vizMode: 'racing_line',
    isPremium: true,
  },
  {
    id: 'vettel_rain_recovery',
    title: 'Last Gasp',
    subtitle: 'Vettel — Brazil 2012',
    driverId: 'vettel',
    raceId: 'vettel_brazil_2012',
    circuitId: 'interlagos',
    driverColor: '#1e41ff',
    theme: 'blueprint',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Drama',
  },
  {
    id: 'alonso_monza_miracle',
    title: 'Monza Miracle',
    subtitle: 'Alonso — Monza 2008',
    driverId: 'alonso',
    raceId: 'alonso_monza_2008',
    circuitId: 'monza',
    driverColor: '#ffd700',
    theme: 'carbon_fiber',
    vizMode: 'racing_line',
    isPremium: true,
  },
  {
    id: 'leclerc_homecoming',
    title: 'Homecoming',
    subtitle: 'Leclerc — Monaco 2024',
    driverId: 'leclerc',
    raceId: 'leclerc_monaco_2024',
    circuitId: 'monaco',
    driverColor: '#dc0000',
    theme: 'monaco_night',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Home Win',
  },
  {
    id: 'norris_first_blood',
    title: 'First Blood',
    subtitle: 'Norris — Miami 2024',
    driverId: 'norris',
    raceId: 'norris_miami_2024',
    circuitId: 'miami',
    driverColor: '#ff8000',
    theme: 'neon_racing',
    vizMode: 'speed_heatmap',
    isPremium: true,
    badge: 'Maiden Win',
  },
  {
    id: 'russell_breakthrough',
    title: "Saturday's Sunday",
    subtitle: 'Russell — São Paulo 2022',
    driverId: 'russell',
    raceId: 'russell_saopaulo_2022',
    circuitId: 'interlagos',
    driverColor: '#00d2be',
    theme: 'carbon_fiber',
    vizMode: 'racing_line',
    isPremium: true,
  },
  {
    id: 'sainz_streak_breaker',
    title: 'Streak Breaker',
    subtitle: 'Sainz — Singapore 2023',
    driverId: 'sainz',
    raceId: 'sainz_singapore_2023',
    circuitId: 'marina_bay',
    driverColor: '#dc0000',
    theme: 'blueprint',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Giant Killer',
  },
  {
    id: 'leclerc_tifosi_dream',
    title: 'Tifosi Dream',
    subtitle: 'Leclerc — Monza 2019',
    driverId: 'leclerc',
    raceId: 'leclerc_monza_2019',
    circuitId: 'monza',
    driverColor: '#dc0000',
    theme: 'vintage_f1',
    vizMode: 'speed_heatmap',
    isPremium: true,
  },
  {
    id: 'verstappen_rain_king',
    title: 'Rain King',
    subtitle: 'Verstappen — Suzuka 2022',
    driverId: 'verstappen',
    raceId: 'verstappen_suzuka_2022',
    circuitId: 'suzuka',
    driverColor: '#1e41ff',
    theme: 'helmet_cam',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Champion',
  },
  {
    id: 'hamilton_pole_perfection',
    title: 'Pole Perfection',
    subtitle: 'Hamilton — Hungary 2020',
    driverId: 'hamilton',
    raceId: 'hamilton_hungary_2020',
    circuitId: 'hungaroring',
    driverColor: '#00d2be',
    theme: 'championship_gold',
    vizMode: 'sector_split',
    isPremium: true,
  },
  {
    id: 'perez_street_king',
    title: 'Street King',
    subtitle: 'Pérez — Baku 2021',
    driverId: 'perez',
    raceId: 'perez_baku_2021',
    circuitId: 'baku',
    driverColor: '#1e41ff',
    theme: 'neon_racing',
    vizMode: 'speed_heatmap',
    isPremium: true,
    badge: 'Survivor',
  },
  {
    id: 'ricciardo_redemption',
    title: 'Redemption',
    subtitle: 'Ricciardo — Monaco 2018',
    driverId: 'ricciardo',
    raceId: 'ricciardo_monaco_2018',
    circuitId: 'monaco',
    driverColor: '#e8911f',
    theme: 'monaco_night',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Iconic',
  },
  {
    id: 'gasly_fairytale',
    title: 'The Fairytale',
    subtitle: 'Gasly — Monza 2020',
    driverId: 'gasly',
    raceId: 'gasly_monza_2020',
    circuitId: 'monza',
    driverColor: '#3b82f6',
    theme: 'carbon_fiber',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Underdog',
  },
  {
    id: 'ocon_against_odds',
    title: 'Against the Odds',
    subtitle: 'Ocon — Hungary 2021',
    driverId: 'ocon',
    raceId: 'ocon_hungary_2021',
    circuitId: 'hungaroring',
    driverColor: '#0093cc',
    theme: 'blueprint',
    vizMode: 'racing_line',
    isPremium: true,
  },
  {
    id: 'piastri_ice_cool',
    title: 'Ice Cool',
    subtitle: 'Piastri — Hungary 2024',
    driverId: 'piastri',
    raceId: 'piastri_hungary_2024',
    circuitId: 'hungaroring',
    driverColor: '#ff8000',
    theme: 'podium_champagne',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Maiden Win',
  },
]
