import type { GalleryItem } from './types'

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'last_lap_king',
    title: 'Last Lap King',
    subtitle: 'Verstappen — Abu Dhabi 2021',
    driverId: 'verstappen',
    raceId: 'verstappen_abu_dhabi_2021',
    circuitId: 'abu_dhabi',
    driverColor: '#1e41ff',
    theme: 'neon_racing',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Historic',
  },
  {
    id: 'seven_nation',
    title: 'Seven Nation',
    subtitle: 'Hamilton — Silverstone 2020',
    driverId: 'hamilton',
    raceId: 'hamilton_silverstone_2020',
    circuitId: 'silverstone',
    driverColor: '#00d2be',
    theme: 'carbon_fiber',
    vizMode: 'racing_line',
    isPremium: false,
  },
  {
    id: 'norris_first_blood',
    title: 'First Blood',
    subtitle: 'Norris — Miami 2024',
    driverId: 'norris',
    raceId: 'norris_miami_2024',
    circuitId: 'miami',
    driverColor: '#ff8000',
    theme: 'neon_racing',
    vizMode: 'speed_heatmap',
    isPremium: true,
    badge: 'Maiden Win',
  },
  {
    id: 'sainz_streak_breaker',
    title: 'Streak Breaker',
    subtitle: 'Sainz — Singapore 2023',
    driverId: 'sainz',
    raceId: 'sainz_singapore_2023',
    circuitId: 'marina_bay',
    driverColor: '#dc0000',
    theme: 'blueprint',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Giant Killer',
  },
  {
    id: 'hamilton_pole_perfection',
    title: 'Pole Perfection',
    subtitle: 'Hamilton — Hungary 2020',
    driverId: 'hamilton',
    raceId: 'hamilton_hungary_2020',
    circuitId: 'hungaroring',
    driverColor: '#00d2be',
    theme: 'championship_gold',
    vizMode: 'sector_split',
    isPremium: true,
  },
  {
    id: 'perez_street_king',
    title: 'Street King',
    subtitle: 'Pérez — Baku 2021',
    driverId: 'perez',
    raceId: 'perez_baku_2021',
    circuitId: 'baku',
    driverColor: '#1e41ff',
    theme: 'neon_racing',
    vizMode: 'speed_heatmap',
    isPremium: true,
    badge: 'Survivor',
  },
  {
    id: 'ocon_against_odds',
    title: 'Against the Odds',
    subtitle: 'Ocon — Hungary 2021',
    driverId: 'ocon',
    raceId: 'ocon_hungary_2021',
    circuitId: 'hungaroring',
    driverColor: '#0093cc',
    theme: 'blueprint',
    vizMode: 'racing_line',
    isPremium: true,
  },
  {
    id: 'piastri_ice_cool',
    title: 'Ice Cool',
    subtitle: 'Piastri — Hungary 2024',
    driverId: 'piastri',
    raceId: 'piastri_hungary_2024',
    circuitId: 'hungaroring',
    driverColor: '#ff8000',
    theme: 'gallery_print',
    vizMode: 'racing_line',
    isPremium: true,
    badge: 'Maiden Win',
  },
  {
    id: 'bearman_dropped_in',
    title: 'Dropped In',
    subtitle: 'Bearman — Jeddah 2024',
    driverId: 'bearman',
    raceId: 'bearman_jeddah_2024',
    circuitId: 'jeddah',
    driverColor: '#dc0000',
    theme: 'ferrari_rosso',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Debut',
  },
  {
    id: 'hulkenberg_long_wait',
    title: 'The Long Wait',
    subtitle: 'Hülkenberg — Silverstone 2025',
    driverId: 'hulkenberg',
    raceId: 'hulkenberg_silverstone_2025',
    circuitId: 'silverstone',
    driverColor: '#00e701',
    theme: 'british_racing_green',
    vizMode: 'speed_heatmap',
    isPremium: false,
    badge: 'Breakthrough',
  },
  {
    id: 'verstappen_neon_nights',
    title: 'Neon Nights',
    subtitle: 'Verstappen — Las Vegas 2023',
    driverId: 'verstappen',
    raceId: 'verstappen_las_vegas_2023',
    circuitId: 'las_vegas',
    driverColor: '#1e41ff',
    theme: 'neon_racing',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Instant Classic',
  },
  {
    id: 'verstappen_orange_army',
    title: 'Orange Army',
    subtitle: 'Verstappen — Zandvoort 2021',
    driverId: 'verstappen',
    raceId: 'verstappen_zandvoort_2021',
    circuitId: 'zandvoort',
    driverColor: '#1e41ff',
    theme: 'redbull_midnight',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Home Hero',
  },
  {
    id: 'raikkonen_one_more_time',
    title: 'One More Time',
    subtitle: 'Räikkönen — Austin 2018',
    driverId: 'raikkonen',
    raceId: 'raikkonen_usa_2018',
    circuitId: 'cota',
    driverColor: '#9b0000',
    theme: 'carbon_mono',
    vizMode: 'sector_split',
    isPremium: true,
    badge: 'Iceman',
  },
  {
    id: 'leclerc_grand_slam',
    title: 'Grand Slam',
    subtitle: 'Leclerc — Melbourne 2022',
    driverId: 'leclerc',
    raceId: 'leclerc_australia_2022',
    circuitId: 'australia',
    driverColor: '#dc0000',
    theme: 'ferrari_rosso',
    vizMode: 'racing_line',
    isPremium: false,
    badge: 'Grand Slam',
  },]
